package co.ratmo.anreal.core.presentation

object AnrealCopy {
    const val ERROR_NO_INTERNET = "error_no_internet"
    const val ERROR_UNAUTHORIZED = "error_unauthorized"
    const val ERROR_FORBIDDEN = "error_forbidden"
    const val ERROR_NOT_FOUND = "error_not_found"
    const val ERROR_TIMEOUT = "error_timeout"
    const val ERROR_CONFLICT = "error_conflict"
    const val ERROR_TOO_MANY_REQUESTS = "error_too_many_requests"
    const val ERROR_SERVER = "error_server"
    const val ERROR_UNKNOWN = "error_unknown"
    const val ERROR_DISK_FULL = "error_disk_full"
    const val ERROR_INVALID_EMAIL = "error_invalid_email"
    const val ERROR_PASSWORD_TOO_SHORT = "error_password_too_short"
    const val ERROR_PASSWORD_MISMATCH = "error_password_mismatch"
    const val ERROR_NAME_REQUIRED = "error_name_required"
    const val ERROR_INVALID_CREDENTIALS = "error_invalid_credentials"
    const val ERROR_EMAIL_TAKEN = "error_email_taken"
    const val ERROR_SIGN_IN_FAILED = "error_sign_in_failed"
    const val ERROR_SIGN_UP_FAILED = "error_sign_up_failed"
    const val ERROR_STORAGE_QUOTA = "error_storage_quota"
    const val ERROR_DOCUMENT_INGEST = "error_document_ingest"
    const val ERROR_IMAGE_LOAD = "error_image_load"
    const val ERROR_REGENERATE_UNAVAILABLE = "error_regenerate_unavailable"
    const val ERROR_SESSION_STALE = "error_session_stale"
    const val ERROR_MODEL_CATALOG_UNAVAILABLE = "error_model_catalog_unavailable"
    const val DIALOG_MODEL_UNAVAILABLE_TITLE = "dialog_model_unavailable_title"
    const val DIALOG_MODEL_UNAVAILABLE_BODY = "dialog_model_unavailable_body"

    const val LABEL_EMAIL = "label_email"
    const val LABEL_PASSWORD = "label_password"
    const val LABEL_NAME = "label_name"
    const val LABEL_CONFIRM_PASSWORD = "label_confirm_password"
    const val LABEL_REMEMBER_ME = "label_remember_me"
    const val ACTION_CONTINUE = "action_continue"
    const val ACTION_LOAD_MORE = "action_load_more"
    const val ACTION_ATTACH = "action_attach"
    const val ACTION_CLOSE = "action_close"
    const val ACTION_PREVIOUS = "action_previous"
    const val ACTION_NEXT = "action_next"
    const val ACTION_SIGNING_IN = "action_signing_in"
    const val ACTION_CREATE_ACCOUNT = "action_create_account"
    const val ACTION_CREATING_ACCOUNT = "action_creating_account"
    const val ACTION_SIGN_IN = "action_sign_in"
    const val AUTH_HAVE_ACCOUNT = "auth_have_account"
    const val AUTH_NEW_HERE = "auth_new_here"
    const val LOGIN_TITLE = "login_title"
    const val LOGIN_SUBTITLE = "login_subtitle"
    const val REGISTER_TITLE = "register_title"
    const val REGISTER_SUBTITLE = "register_subtitle"
    const val PLACEHOLDER_EMAIL = "placeholder_email"
    const val PLACEHOLDER_PASSWORD = "placeholder_password"
    const val PLACEHOLDER_NAME = "placeholder_name"
    const val PLACEHOLDER_PASSWORD_NEW = "placeholder_password_new"
    const val PLACEHOLDER_PASSWORD_REPEAT = "placeholder_password_repeat"
    const val PLACEHOLDER_PROJECT_NAME = "placeholder_project_name"
    const val PLACEHOLDER_PROJECT_DESCRIPTION = "placeholder_project_description"
    const val PLACEHOLDER_SESSION_TITLE = "placeholder_session_title"
    const val SPLASH_VERSION = "splash_version"
    const val SPLASH_CREDIT = "splash_credit"
    const val CD_APP_MARK = "cd_app_mark"
    const val BOARDING_DOCUMENTS_TITLE = "boarding_documents_title"
    const val BOARDING_DOCUMENTS_BODY = "boarding_documents_body"
    const val BOARDING_WEB_TITLE = "boarding_web_title"
    const val BOARDING_WEB_BODY = "boarding_web_body"
    const val BOARDING_IMAGES_TITLE = "boarding_images_title"
    const val BOARDING_IMAGES_BODY = "boarding_images_body"
    const val CD_BOARDING_PAGE = "cd_boarding_page"
    const val BOARDING_USER_PROMPT = "boarding_user_prompt"
    const val BOARDING_ASSISTANT_REPLY = "boarding_assistant_reply"
    const val BOARDING_CITATION = "boarding_citation"
    const val BOARDING_WEB_TOOL = "boarding_web_tool"
    const val BOARDING_WEB_SOURCE = "boarding_web_source"
    const val BOARDING_IMAGE_CAPTION = "boarding_image_caption"
    const val BOARDING_TAGLINE = "boarding_tagline"
    const val BOARDING_APPROVAL_TITLE = "boarding_approval_title"
    const val BOARDING_APPROVAL_ACTION = "boarding_approval_action"
    const val BOARDING_IMAGE_PROMPT = "boarding_image_prompt"
    const val BOARDING_DOCUMENT_NAME = "boarding_document_name"
    const val BOARDING_SOURCE_ONE_NAME = "boarding_source_one_name"
    const val BOARDING_SOURCE_ONE_DETAIL = "boarding_source_one_detail"
    const val BOARDING_SOURCE_TWO_NAME = "boarding_source_two_name"
    const val BOARDING_SOURCE_TWO_DETAIL = "boarding_source_two_detail"
    const val BOARDING_IMAGE_EDIT = "boarding_image_edit"
    const val AUTH_LOGIN_NOTE_TITLE = "auth_login_note_title"
    const val AUTH_LOGIN_NOTE_BODY = "auth_login_note_body"
    const val AUTH_REGISTER_NOTE_TITLE = "auth_register_note_title"
    const val AUTH_REGISTER_NOTE_BODY = "auth_register_note_body"
    const val ACTION_RETRY = "action_retry"
    const val ACTION_SHOW_PASSWORD = "action_show_password"
    const val ACTION_HIDE_PASSWORD = "action_hide_password"
    const val STATUS_LOADING = "status_loading"
    const val STATUS_THINKING = "status_thinking"
    const val STATUS_IMAGE_LOADED = "status_image_loaded"
    const val ERROR_RUN_ACTIVE = "error_run_active"
    const val CHAT_EMPTY_TITLE = "chat_empty_title"
    const val CHAT_EMPTY_BODY = "chat_empty_body"
    const val CHAT_SESSIONS_EMPTY_TITLE = "chat_sessions_empty_title"
    const val CHAT_SESSIONS_EMPTY_BODY = "chat_sessions_empty_body"
    const val ACTION_NEW_CHAT = "action_new_chat"
    const val ACTION_SEND = "action_send"
    const val ACTION_STOP = "action_stop"
    const val ACTION_CHOOSE_MODEL = "action_choose_model"
    const val ACTION_RESUME = "action_resume"
    const val COMPOSER_PLACEHOLDER = "composer_placeholder"
    const val LABEL_THOUGHT = "label_thought"
    const val LABEL_THINKING_LIVE = "label_thinking_live"
    const val LABEL_THOUGHT_FOR = "label_thought_for"
    const val LABEL_WAITING_SUMMARY = "label_waiting_summary"
    const val LABEL_NO_SUMMARY = "label_no_summary"
    const val LABEL_TOOL_REQUEST = "label_tool_request"
    const val LABEL_TOOL_RESULT = "label_tool_result"
    const val LABEL_TOOL_WORKING = "label_tool_working"
    const val LABEL_TOOL_WAITING_REQUEST = "label_tool_waiting_request"
    const val CD_TOGGLE_REASONING = "cd_toggle_reasoning"
    const val CD_TOGGLE_TOOL = "cd_toggle_tool"
    const val CD_COPY_MESSAGE = "cd_copy_message"
    const val CD_ADD_CONTEXT = "cd_add_context"
    const val CD_EDIT_MESSAGE = "cd_edit_message"
    const val CD_REGENERATE = "cd_regenerate"
    const val CD_FEATURES = "cd_features"
    const val CD_ATTACH = "cd_attach"
    const val CD_MODEL = "cd_model"
    const val LABEL_MODEL = "label_model"
    const val LABEL_REASONING = "label_reasoning"
    const val LABEL_REASONING_NONE = "label_reasoning_none"
    const val MODELS_EMPTY = "models_empty"
    const val LABEL_WEB_SEARCH = "label_web_search"
    const val LABEL_IMAGE_GEN = "label_image_gen"
    const val LABEL_DEEP_RESEARCH = "label_deep_research"
    const val LABEL_ATTACH = "label_attach"
    const val LABEL_ATTACH_PHOTOS = "label_attach_photos"
    const val LABEL_ATTACH_LOCAL = "label_attach_local"
    const val LABEL_ATTACH_LIBRARY = "label_attach_library"
    const val LABEL_DOCUMENT_LIBRARY = "label_document_library"
    const val LABEL_SEARCH_DOCUMENTS = "label_search_documents"
    const val PLACEHOLDER_SEARCH_DOCUMENTS = "placeholder_search_documents"
    const val LABEL_SESSION_IMAGES = "label_session_images"
    const val IMAGE_CONTEXT_HELP = "image_context_help"
    const val CD_UNPIN_IMAGE = "cd_unpin_image"
    const val LABEL_CONTEXT_USAGE = "label_context_usage"
    const val CD_CONTEXT_USAGE = "cd_context_usage"
    const val CD_SCROLL_TO_BOTTOM = "cd_scroll_to_bottom"
    const val CD_LOADING_OLDER_MESSAGES = "cd_loading_older_messages"
    const val LABEL_CONTEXT_MODEL = "label_context_model"
    const val LABEL_CONTEXT_TOKENS = "label_context_tokens"
    const val LABEL_CONTEXT_USED = "label_context_used"
    const val LABEL_CONTEXT_WINDOW = "label_context_window"
    const val LABEL_CONTEXT_THRESHOLD = "label_context_threshold"
    const val LABEL_CONTEXT_TARGET = "label_context_target"
    const val LABEL_SEARCH = "label_search"
    const val PLACEHOLDER_SEARCH_WORKSPACE = "placeholder_search_workspace"
    const val CD_WORKSPACE_SEARCH = "cd_workspace_search"
    const val CD_CARD_ACTIONS = "cd_card_actions"
    const val CD_GRID_VIEW = "cd_grid_view"
    const val CD_LIST_VIEW = "cd_list_view"
    const val LABEL_FILTER_ALL = "label_filter_all"
    const val LABEL_FILTER_RECENT = "label_filter_recent"
    const val LABEL_FILTER_SHARED = "label_filter_shared"
    const val LABEL_SORT_UPDATED = "label_sort_updated"
    const val LABEL_SORT_OPENED = "label_sort_opened"
    const val LABEL_SORT_NAME = "label_sort_name"
    const val LABEL_DOCUMENT_PREVIEW = "label_document_preview"
    const val LABEL_DOCUMENT_IMAGE = "label_document_image"
    const val LABEL_APPEARANCE = "label_appearance"
    const val APPEARANCE_SECTION_BODY = "appearance_section_body"
    const val LABEL_ACCOUNT_PREFERENCES = "label_account_preferences"
    const val LABEL_APPEARANCE_DESCRIPTION = "label_appearance_description"
    const val LABEL_USAGE_DESCRIPTION = "label_usage_description"
    const val LABEL_PERSONALIZATION_DESCRIPTION = "label_personalization_description"
    const val LABEL_HELP_FEEDBACK = "label_help_feedback"
    const val LABEL_HELP_FEEDBACK_DESCRIPTION = "label_help_feedback_description"
    const val LABEL_ABOUT = "label_about"
    const val LABEL_ABOUT_DESCRIPTION = "label_about_description"
    const val LABEL_ACCOUNT_FOOTER = "label_account_footer"
    const val LABEL_THEME_CURRENT = "label_theme_current"
    const val LABEL_DYNAMIC_COLOR_DESCRIPTION = "label_dynamic_color_description"
    const val LABEL_DYNAMIC_COLOR_HELPER = "label_dynamic_color_helper"
    const val LABEL_REDUCE_MOTION_DESCRIPTION = "label_reduce_motion_description"
    const val LABEL_REDUCE_MOTION_HELPER = "label_reduce_motion_helper"
    const val LABEL_REDUCE_TRANSPARENCY_DESCRIPTION = "label_reduce_transparency_description"
    const val LABEL_REDUCE_TRANSPARENCY_HELPER = "label_reduce_transparency_helper"
    const val LABEL_PREVIEW_WITH_FROST = "label_preview_with_frost"
    const val LABEL_PREVIEW_GLASS_TOP_BAR = "label_preview_glass_top_bar"
    const val LABEL_PREVIEW_REDUCED = "label_preview_reduced"
    const val LABEL_PREVIEW_SURFACE_CONTAINER = "label_preview_surface_container"
    const val LABEL_API_STATUS = "label_api_status"
    const val STATUS_CHECKING = "status_checking"
    const val STATUS_CONNECTED = "status_connected"
    const val STATUS_UNAVAILABLE = "status_unavailable"
    const val STATUS_UPLOAD_QUEUED = "status_upload_queued"
    const val STATUS_UPLOAD_PROCESSING = "status_upload_processing"
    const val STATUS_UPLOAD_UPLOADING = "status_upload_uploading"
    const val STATUS_UPLOAD_FAILED = "status_upload_failed"
    const val LABEL_THEME = "label_theme"
    const val LABEL_THEME_SYSTEM = "label_theme_system"
    const val LABEL_THEME_LIGHT = "label_theme_light"
    const val LABEL_THEME_DARK = "label_theme_dark"
    const val LABEL_DYNAMIC_COLOR = "label_dynamic_color"
    const val LABEL_REDUCE_MOTION = "label_reduce_motion"
    const val LABEL_REDUCE_TRANSPARENCY = "label_reduce_transparency"
    const val ATTACH_PHOTOS_BODY = "attach_photos_body"
    const val ATTACH_LOCAL_BODY = "attach_local_body"
    const val ATTACH_LIBRARY_BODY = "attach_library_body"
    const val ATTACH_LIBRARY_EMPTY = "attach_library_empty"
    const val TOAST_COPIED = "toast_copied"
    const val FEATURE_UNAVAILABLE = "feature_unavailable"
    const val CD_OPEN_CHATS = "cd_open_chats"
    const val LABEL_CHATS = "label_chats"
    const val LABEL_UNREAD = "label_unread"
    const val DIALOG_RUN_ACTIVE_TITLE = "dialog_run_active_title"
    const val ACTION_WAIT = "action_wait"
    const val ACTION_RENAME = "action_rename"
    const val ACTION_DELETE = "action_delete"
    const val ACTION_SHARE = "action_share"
    const val ACTION_VIEW_PROJECT = "action_view_project"
    const val ACTION_VIEW_DOCUMENT = "action_view_document"
    const val ACTION_VIEW_PROJECT_DESCRIPTION = "action_view_project_description"
    const val ACTION_VIEW_DOCUMENT_DESCRIPTION = "action_view_document_description"
    const val ACTION_RENAME_DESCRIPTION = "action_rename_description"
    const val ACTION_SHARE_DESCRIPTION = "action_share_description"
    const val ACTION_DELETE_DESCRIPTION = "action_delete_description"
    const val LABEL_PROJECT_ACTIONS = "label_project_actions"
    const val LABEL_DOCUMENT_ACTIONS = "label_document_actions"
    const val LABEL_LOADED = "label_loaded"
    const val ACTION_PULL_TO_REFRESH = "action_pull_to_refresh"
    const val ACTION_DELETING = "action_deleting"
    const val ACTION_CANCEL = "action_cancel"
    const val DIALOG_RENAME_TITLE = "dialog_rename_title"
    const val DIALOG_DELETE_TITLE = "dialog_delete_title"
    const val DIALOG_DELETE_BODY = "dialog_delete_body"
    const val DIALOG_DELETE_BODY_RUNNING = "dialog_delete_body_running"
    const val TOAST_CHAT_DELETED = "toast_chat_deleted"
    const val CD_SESSION_MENU = "cd_session_menu"
    const val ERROR_TITLE_REQUIRED = "error_title_required"
    const val LABEL_SESSION_TITLE = "label_session_title"
    const val TOOL_STATUS_WORKING = "tool_status_working"
    const val TOOL_STATUS_DONE = "tool_status_done"
    const val TOOL_STATUS_ERROR = "tool_status_error"
    const val TOOL_RUNNING_FALLBACK = "tool_running_fallback"
    const val TOOL_FIND_DOCUMENTS = "tool_find_documents"
    const val TOOL_SEARCH_DOCUMENT_PAGES = "tool_search_document_pages"
    const val TOOL_GET_DOCUMENT_NEXT_PAGE = "tool_get_document_next_page"
    const val TOOL_WEB_SEARCH = "tool_web_search"
    const val TOOL_WEB_FETCH = "tool_web_fetch"
    const val TOOL_GENERATE_IMAGE = "tool_generate_image"
    const val TOOL_EDIT_IMAGE = "tool_edit_image"
    const val TOOL_VIEW_IMAGE = "tool_view_image"
    const val TOOL_DESCRIPTIVE_STATS = "tool_descriptive_stats"
    const val TOOL_PEARSON = "tool_pearson"
    const val TOOL_LINEAR_REGRESSION = "tool_linear_regression"
    const val TOOL_PAGE_IMAGES = "tool_page_images"
    const val TOOL_CLARIFICATION = "tool_clarification"
    const val TOOL_RESOLVE_LIBRARY = "tool_resolve_library"
    const val TOOL_QUERY_DOCS = "tool_query_docs"
    const val ERROR_NO_ACTIVE_RUN = "error_no_active_run"
    const val ERROR_INTERACTION_GONE = "error_interaction_gone"
    const val ERROR_INTERACTION_EXPIRED = "error_interaction_expired"
    const val ERROR_INTERACTION_HANDLED = "error_interaction_handled"
    const val ERROR_INTERACTION_UNAVAILABLE = "error_interaction_unavailable"
    const val ERROR_INTERACTION_INVALID = "error_interaction_invalid"
    const val ERROR_SHARE_NOT_FOUND = "error_share_not_found"
    const val ERROR_NO_ACTIVE_SHARE = "error_no_active_share"
    const val ERROR_FORK_TARGET_NOT_FOUND = "error_fork_target_not_found"
    const val ERROR_FORK_INVALID = "error_fork_invalid"
    const val ERROR_SHARE_UNAVAILABLE = "error_share_unavailable"
    const val ACTION_QUEUE = "action_queue"
    const val ACTION_SEND_NOW = "action_send_now"
    const val ACTION_SEND_QUEUE = "action_send_queue"
    const val ACTION_SEND_NEW_MESSAGE = "action_send_new_message"
    const val DIALOG_QUEUE_CONFLICT_TITLE = "dialog_queue_conflict_title"
    const val DIALOG_QUEUE_CONFLICT_BODY = "dialog_queue_conflict_body"
    const val LABEL_QUEUED_COUNT = "label_queued_count"
    const val LABEL_EDITING = "label_editing"
    const val CD_HIDE_QUEUE = "cd_hide_queue"
    const val CD_SHOW_QUEUE = "cd_show_queue"
    const val CD_REMOVE_QUEUED = "cd_remove_queued"
    const val CD_EXPAND_QUEUE = "cd_expand_queue"
    const val LABEL_APP_NAME = "label_app_name"
    const val LABEL_WORKSPACE = "label_workspace"
    const val LABEL_ALL_CHATS = "label_all_chats"
    const val LABEL_PROJECTS = "label_projects"
    const val LABEL_DOCUMENTS = "label_documents"
    const val LABEL_IMAGES = "label_images"
    const val LABEL_SITES = "label_sites"
    const val LABEL_TASKS = "label_tasks"
    const val LABEL_SCHEDULES = "label_schedules"
    const val LABEL_ARTIFACTS = "label_artifacts"
    const val LABEL_ALL = "label_all"
    const val LABEL_CAPTION = "label_caption"
    const val ARTIFACTS_OPEN_TASKS = "artifacts_open_tasks"
    const val ARTIFACTS_OPEN_SCHEDULES = "artifacts_open_schedules"
    const val ARTIFACTS_EMPTY = "artifacts_empty"
    const val ARTIFACTS_NO_SCOPE = "artifacts_no_scope"
    const val LABEL_TITLE = "label_title"
    const val LABEL_PROMPT = "label_prompt"
    const val LABEL_RUN_AT = "label_run_at"
    const val LABEL_DUE_DATE = "label_due_date"
    const val TASKS_NEW_TITLE = "tasks_new_title"
    const val SCHEDULES_NEW_TITLE = "schedules_new_title"
    const val TASKS_EDIT_TITLE = "tasks_edit_title"
    const val TASKS_SUBTASKS_TITLE = "tasks_subtasks_title"
    const val TASKS_ADD_SUBTASK = "tasks_add_subtask"
    const val SITES_EMPTY = "sites_empty"
    const val SITES_NO_SCOPE = "sites_no_scope"
    const val TASKS_EMPTY = "tasks_empty"
    const val TASKS_NO_SCOPE = "tasks_no_scope"
    const val SCHEDULES_EMPTY = "schedules_empty"
    const val SCHEDULES_NO_SCOPE = "schedules_no_scope"
    const val ERROR_DUE_DATE_INVALID = "error_due_date_invalid"
    const val ERROR_PROMPT_REQUIRED = "error_prompt_required"
    const val ERROR_NOTHING_TO_UPDATE = "error_nothing_to_update"
    const val LABEL_RECENT_PROJECTS = "label_recent_projects"
    const val LABEL_PROJECT_CHAT_TITLE = "label_project_chat_title"
    const val LABEL_TODAY = "label_today"
    const val LABEL_YESTERDAY = "label_yesterday"
    const val LABEL_EARLIER = "label_earlier"
    const val CD_OPEN_DOCUMENTS = "cd_open_documents"
    const val LABEL_ACTIVE_DOCUMENTS = "label_active_documents"
    const val LABEL_CITED_DOCUMENTS = "label_cited_documents"
    const val LABEL_DOCUMENTS_NONE = "label_documents_none"
    const val LABEL_DOCUMENTS_SUMMARY = "label_documents_summary"
    const val LABEL_CITATION_COUNT = "label_citation_count"
    const val CD_REMOVE_DOCUMENT = "cd_remove_document"
    const val DOCUMENTS_EMPTY_BODY = "documents_empty_body"
    const val ACTION_SETTINGS = "action_settings"
    const val ACTION_LOG_OUT = "action_log_out"
    const val ACTION_LOGGING_OUT = "action_logging_out"
    const val DIALOG_SIGN_OUT_TITLE = "dialog_sign_out_title"
    const val DIALOG_SIGN_OUT_BODY = "dialog_sign_out_body"
    const val CD_ACCOUNT_MENU = "cd_account_menu"
    const val CD_OPEN_ACCOUNT = "cd_open_account"
    const val CD_BACK = "cd_back"
    const val CD_SCROLL_TABS_BACK = "cd_scroll_tabs_back"
    const val CD_SCROLL_TABS_FORWARD = "cd_scroll_tabs_forward"
    const val LABEL_ACCOUNT = "label_account"
    const val LABEL_USAGE = "label_usage"
    const val LABEL_PERSONALIZATION = "label_personalization"
    const val ACCOUNT_SECTION_BODY = "account_section_body"
    const val ACCOUNT_EMAIL_EMPTY = "account_email_empty"
    const val USAGE_SECTION_BODY = "usage_section_body"
    const val USAGE_EMPTY = "usage_empty"
    const val PERSONALIZATION_SECTION_BODY = "personalization_section_body"
    const val PERSONALIZATION_EMPTY = "personalization_empty"
    const val LABEL_STORAGE = "label_storage"
    const val LABEL_REQUESTS = "label_requests"
    const val LABEL_TOTAL_TOKENS = "label_total_tokens"
    const val LABEL_INPUT_TOKENS = "label_input_tokens"
    const val LABEL_OUTPUT_TOKENS = "label_output_tokens"
    const val LABEL_CACHED_TOKENS = "label_cached_tokens"
    const val LABEL_BY_MODEL = "label_by_model"
    const val LABEL_BY_REASONING = "label_by_reasoning"
    const val LABEL_PROFILE_FACTS = "label_profile_facts"
    const val LABEL_PROJECT_PROFILES = "label_project_profiles"
    const val ACTION_RESET = "action_reset"
    const val ACTION_RESETTING = "action_resetting"
    const val DIALOG_RESET_PROFILE_TITLE = "dialog_reset_profile_title"
    const val DIALOG_RESET_PROFILE_BODY = "dialog_reset_profile_body"
    const val TOAST_PROFILE_RESET = "toast_profile_reset"
    const val ACTION_NEW_PROJECT = "action_new_project"
    const val ACTION_CREATE = "action_create"
    const val LABEL_DESCRIPTION = "label_description"
    const val LABEL_IMAGE = "label_image"
    const val PROJECTS_EMPTY = "projects_empty"
    const val PROJECT_DESCRIPTION_EMPTY = "project_description_empty"
    const val DOCUMENTS_LIBRARY_EMPTY = "documents_library_empty"
    const val IMAGES_EMPTY = "images_empty"
    const val DIALOG_DELETE_WORKSPACE_TITLE = "dialog_delete_workspace_title"
    const val DIALOG_DELETE_WORKSPACE_BODY = "dialog_delete_workspace_body"
    const val ERROR_FILE_TOO_LARGE = "error_file_too_large"
    const val ERROR_FILE_READ = "error_file_read"
    const val TOAST_UPLOAD_COMPLETE = "toast_upload_complete"
    const val APPROVAL_TITLE = "approval_title"
    const val CLARIFICATION_TITLE = "clarification_title"
    const val ACTION_ALLOW_ONCE = "action_allow_once"
    const val ACTION_ALLOW_SESSION = "action_allow_session"
    const val ACTION_REJECT = "action_reject"
    const val ACTION_SUBMIT = "action_submit"
    const val IMAGE_OVERRIDE_TITLE = "image_override_title"
    const val DIALOG_SHARE_TITLE = "dialog_share_title"
    const val DIALOG_SHARE_BODY = "dialog_share_body"
    const val DIALOG_SHARE_NO_LINK = "dialog_share_no_link"
    const val ACTION_CREATE_LINK = "action_create_link"
    const val ACTION_CREATING_LINK = "action_creating_link"
    const val ACTION_COPY_LINK = "action_copy_link"
    const val ACTION_DEACTIVATE_LINKS = "action_deactivate_links"
    const val ACTION_DEACTIVATING_LINKS = "action_deactivating_links"
    const val DIALOG_DEACTIVATE_SHARES_TITLE = "dialog_deactivate_shares_title"
    const val DIALOG_DEACTIVATE_SHARES_BODY = "dialog_deactivate_shares_body"
    const val TOAST_SHARE_LINK_COPIED = "toast_share_link_copied"
    const val TOAST_SHARES_DEACTIVATED = "toast_shares_deactivated"
    const val TOAST_SHARE_CREATED = "toast_share_created"
    const val CD_SHARE_CHAT = "cd_share_chat"
    const val SHARED_CHAT_TITLE = "shared_chat_title"
    const val SHARED_CHAT_SUBTITLE = "shared_chat_subtitle"
    const val SHARED_CHAT_EMPTY = "shared_chat_empty"
    const val SHARED_CHAT_SIGN_IN_CTA = "shared_chat_sign_in_cta"
    const val SHARED_CHAT_FORKING = "shared_chat_forking"
    const val SHARED_CHAT_FORK_CHIP = "shared_chat_fork_chip"
    const val SHARED_CHAT_GATE_BODY = "shared_chat_gate_body"
    const val LABEL_SKILLS = "label_skills"
    const val LABEL_MCP = "label_mcp"
    const val CD_MANAGE_SKILLS = "cd_manage_skills"
    const val CD_MANAGE_MCP = "cd_manage_mcp"
    const val SKILLS_ON = "skills_on"
    const val SKILLS_OFF = "skills_off"
    const val SKILLS_EMPTY = "skills_empty"
    const val MCP_ON = "mcp_on"
    const val MCP_OFF = "mcp_off"
    const val MCP_EMPTY = "mcp_empty"
    const val SKILLS_LIST_EMPTY_TITLE = "skills_list_empty_title"
    const val SKILLS_LIST_EMPTY_BODY = "skills_list_empty_body"
    const val SKILLS_LOAD_ERROR = "skills_load_error"
    const val MCP_LIST_EMPTY_TITLE = "mcp_list_empty_title"
    const val MCP_LIST_EMPTY_BODY = "mcp_list_empty_body"
    const val MCP_LOAD_ERROR = "mcp_load_error"
    const val ACTION_NEW = "action_new"
    const val ACTION_SAVE = "action_save"
    const val ACTION_SAVING = "action_saving"
    const val ACTION_UPLOAD_MD = "action_upload_md"
    const val ACTION_ADD_HEADER = "action_add_header"
    const val SKILL_STATUS_DRAFT = "skill_status_draft"
    const val SKILL_STATUS_INVALID = "skill_status_invalid"
    const val SKILL_EDITOR_NEW_TITLE = "skill_editor_new_title"
    const val SKILL_EDITOR_EDIT_TITLE = "skill_editor_edit_title"
    const val SKILL_NAME_PLACEHOLDER = "skill_name_placeholder"
    const val SKILL_DESCRIPTION_PLACEHOLDER = "skill_description_placeholder"
    const val SKILL_BODY_LABEL = "skill_body_label"
    const val SKILL_BODY_PLACEHOLDER = "skill_body_placeholder"
    const val DIALOG_DELETE_SKILL_TITLE = "dialog_delete_skill_title"
    const val DIALOG_DELETE_SKILL_BODY = "dialog_delete_skill_body"
    const val CD_EDIT_SKILL = "cd_edit_skill"
    const val CD_DELETE_SKILL = "cd_delete_skill"
    const val CD_TOGGLE_SKILL = "cd_toggle_skill"
    const val MCP_EDITOR_NEW_TITLE = "mcp_editor_new_title"
    const val MCP_EDITOR_EDIT_TITLE = "mcp_editor_edit_title"
    const val MCP_URL_LABEL = "mcp_url_label"
    const val MCP_URL_PLACEHOLDER = "mcp_url_placeholder"
    const val MCP_AUTH_LABEL = "mcp_auth_label"
    const val MCP_AUTH_NONE = "mcp_auth_none"
    const val MCP_AUTH_BEARER = "mcp_auth_bearer"
    const val MCP_TOKEN_LABEL = "mcp_token_label"
    const val MCP_TOKEN_PLACEHOLDER = "mcp_token_placeholder"
    const val MCP_TOKEN_KEEP = "mcp_token_keep"
    const val MCP_HEADERS_LABEL = "mcp_headers_label"
    const val MCP_TEST_ACTION = "mcp_test_action"
    const val MCP_TESTING_ACTION = "mcp_testing_action"
    const val MCP_RETEST_ACTION = "mcp_retest_action"
    const val MCP_TEST_FIRST = "mcp_test_first"
    const val MCP_URL_RETEST = "mcp_url_retest"
    const val MCP_TOOLS_MIN = "mcp_tools_min"
    const val MCP_TOOLS_TITLE = "mcp_tools_title"
    const val MCP_TOOLS_COUNT = "mcp_tools_count"
    const val MCP_SERVER_UNTESTED = "mcp_server_untested"
    const val MCP_TEST_OK = "mcp_test_ok"
    const val DIALOG_DELETE_MCP_TITLE = "dialog_delete_mcp_title"
    const val DIALOG_DELETE_MCP_BODY = "dialog_delete_mcp_body"
    const val CD_EDIT_SERVER = "cd_edit_server"
    const val CD_DELETE_SERVER = "cd_delete_server"
    const val CD_TOGGLE_SERVER = "cd_toggle_server"
    const val CD_REMOVE_HEADER = "cd_remove_header"
    const val LABEL_HEADER_NAME = "label_header_name"
    const val LABEL_HEADER_VALUE = "label_header_value"
    const val SITE_PREVIEW_ACTION = "site_preview_action"
    const val SITE_DOWNLOAD_ACTION = "site_download_action"
    const val SITE_RETRY_ACTION = "site_retry_action"
    const val SITE_HIDE = "site_hide"
    const val SITE_SHOW = "site_show"
    const val SITE_ROLLBACK = "site_rollback"
    const val SITE_VERSION_STABLE = "site_version_stable"
    const val SITE_VERSION_FAILED = "site_version_failed"
    const val SITE_VERSION_PLAIN = "site_version_plain"
    const val SITE_STEP_STARTING = "site_step_starting"
    const val SITE_STEP_PLANNING = "site_step_planning"
    const val SITE_STEP_BUILDING = "site_step_building"
    const val SITE_STEP_BUNDLING = "site_step_bundling"
    const val SITE_STEP_PREVIEW = "site_step_preview"
    const val SITE_STEP_READY = "site_step_ready"
    const val SITE_PREVIEW_TITLE = "site_preview_title"
    const val SITE_PREVIEW_UNAVAILABLE = "site_preview_unavailable"
    const val SITE_DOWNLOAD_SAVED = "site_download_saved"
    const val SITE_DOWNLOAD_FAILED = "site_download_failed"
    const val SITE_OPEN_CHAT = "site_open_chat"
    const val SITE_CONTINUE = "site_continue"
    const val SITE_CONTINUE_DRAFT = "site_continue_draft"

    fun get(key: String): String {
        return when (key) {
            ERROR_NO_INTERNET -> "Check your connection and try again."
            ERROR_UNAUTHORIZED -> "Sign in to continue."
            ERROR_FORBIDDEN -> "You don't have access to that."
            ERROR_NOT_FOUND -> "We couldn't find that."
            ERROR_TIMEOUT -> "That took too long. Try again."
            ERROR_CONFLICT -> "That conflicts with the current state. Try again."
            ERROR_TOO_MANY_REQUESTS -> "Too many attempts. Wait a moment and try again."
            ERROR_SERVER -> "The server had a problem. Try again."
            ERROR_UNKNOWN -> "Something went wrong. Try again."
            ERROR_DISK_FULL -> "Not enough storage to finish that."
            ERROR_INVALID_EMAIL -> "Enter a valid email address."
            ERROR_PASSWORD_TOO_SHORT -> "Password must be at least 8 characters."
            ERROR_PASSWORD_MISMATCH -> "Passwords do not match."
            ERROR_NAME_REQUIRED -> "Name is required."
            ERROR_INVALID_CREDENTIALS -> "Invalid email or password."
            ERROR_EMAIL_TAKEN -> "An account with that email already exists."
            ERROR_SIGN_IN_FAILED -> "Could not sign in. Check your connection and try again."
            ERROR_SIGN_UP_FAILED -> "Could not create an account. Try again."
            LABEL_EMAIL -> "Email"
            LABEL_PASSWORD -> "Password"
            LABEL_NAME -> "Name"
            LABEL_CONFIRM_PASSWORD -> "Confirm password"
            LABEL_REMEMBER_ME -> "Remember me"
            ACTION_CONTINUE -> "Continue"
            ACTION_SIGNING_IN -> "Signing in…"
            ACTION_CREATE_ACCOUNT -> "Create account"
            ACTION_CREATING_ACCOUNT -> "Creating account…"
            ACTION_SIGN_IN -> "Sign in"
            AUTH_HAVE_ACCOUNT -> "Already have an account?"
            AUTH_NEW_HERE -> "New here?"
            LOGIN_TITLE -> "Welcome back"
            LOGIN_SUBTITLE -> "Sign in to continue with your documents, sources, and project context."
            REGISTER_TITLE -> "Build your private workspace"
            REGISTER_SUBTITLE -> "Create one account for grounded chats, research, and visual work."
            PLACEHOLDER_EMAIL -> "you@company.com"
            PLACEHOLDER_PASSWORD -> "Your password"
            PLACEHOLDER_NAME -> "Ada Lovelace"
            PLACEHOLDER_PASSWORD_NEW -> "At least 8 characters"
            PLACEHOLDER_PASSWORD_REPEAT -> "Repeat your password"
            PLACEHOLDER_PROJECT_NAME -> "e.g. Research sprint"
            PLACEHOLDER_PROJECT_DESCRIPTION -> "What is this project about?"
            PLACEHOLDER_SESSION_TITLE -> "Give this chat a name"
            SPLASH_VERSION -> "Anreal v{0}"
            SPLASH_CREDIT -> "Presented by Ratmo.co"
            CD_APP_MARK -> "Anreal"
            BOARDING_DOCUMENTS_TITLE -> "Ask, then verify"
            BOARDING_DOCUMENTS_BODY ->
                "Ground every answer in your files and jump straight to the cited page."
            BOARDING_WEB_TITLE -> "Research on your terms"
            BOARDING_WEB_BODY ->
                "Bring in fresh web sources only when you allow it, without leaving the thread."
            BOARDING_IMAGES_TITLE -> "Turn context into visuals"
            BOARDING_IMAGES_BODY ->
                "Generate, edit, and organize images beside the chats and projects that shaped them."
            CD_BOARDING_PAGE -> "Feature {0} of {1}"
            BOARDING_USER_PROMPT -> "Where is the renewal risk?"
            BOARDING_ASSISTANT_REPLY ->
                "Two enterprise accounts are delayed."
            BOARDING_CITATION -> "Board pack · pp. 12–14"
            BOARDING_WEB_TOOL -> "Recent renewal coverage"
            BOARDING_WEB_SOURCE -> "4 cited sources · last 30 days"
            BOARDING_IMAGE_CAPTION -> "Saved to Q3 review"
            BOARDING_TAGLINE -> "A private AI workspace"
            BOARDING_APPROVAL_TITLE -> "Web search needs your approval"
            BOARDING_APPROVAL_ACTION -> "Allow once"
            BOARDING_IMAGE_PROMPT -> "Create a clean risk heatmap"
            BOARDING_DOCUMENT_NAME -> "Board pack.pdf"
            BOARDING_SOURCE_ONE_NAME -> "Reuters"
            BOARDING_SOURCE_ONE_DETAIL -> "Renewal outlook"
            BOARDING_SOURCE_TWO_NAME -> "Trade brief"
            BOARDING_SOURCE_TWO_DETAIL -> "Enterprise cycles"
            BOARDING_IMAGE_EDIT -> "Edit in the same thread"
            AUTH_LOGIN_NOTE_TITLE -> "Pick up where you left off"
            AUTH_LOGIN_NOTE_BODY -> "Your chats, sources, and project context stay together."
            AUTH_REGISTER_NOTE_TITLE -> "Private by default"
            AUTH_REGISTER_NOTE_BODY -> "Your documents and chats stay inside your account."
            ACTION_RETRY -> "Retry"
            ACTION_SHOW_PASSWORD -> "Show password"
            ACTION_HIDE_PASSWORD -> "Hide password"
            STATUS_LOADING -> "Loading"
            STATUS_THINKING -> "Thinking"
            STATUS_IMAGE_LOADED -> "Image loaded"
            ERROR_RUN_ACTIVE -> "This chat is already running. Resume it or wait for it to finish."
            ERROR_STORAGE_QUOTA -> "Document storage is full. Delete a document before uploading another file."
            ERROR_DOCUMENT_INGEST -> "The document could not be processed. Try uploading it again."
            ERROR_IMAGE_LOAD -> "The image could not be loaded."
            ERROR_REGENERATE_UNAVAILABLE -> "This message cannot be regenerated yet. Reload the conversation and try again."
            ERROR_SESSION_STALE -> "This conversation changed elsewhere. The latest messages have been reloaded."
            ERROR_MODEL_CATALOG_UNAVAILABLE -> "The model list could not be loaded. Retry before sending."
            DIALOG_MODEL_UNAVAILABLE_TITLE -> "Model unavailable"
            DIALOG_MODEL_UNAVAILABLE_BODY ->
                "The model “{0}” is no longer available. Choose another model to continue."
            CHAT_EMPTY_TITLE -> "Ask anything about your documents"
            CHAT_EMPTY_BODY -> "Upload a PDF or image, then ask questions."
            CHAT_SESSIONS_EMPTY_TITLE -> "No chats yet"
            CHAT_SESSIONS_EMPTY_BODY -> "Start a conversation about your documents."
            ACTION_NEW_CHAT -> "New chat"
            ACTION_SEND -> "Send"
            ACTION_STOP -> "Stop"
            ACTION_CHOOSE_MODEL -> "Choose model"
            ACTION_LOAD_MORE -> "Load more"
            ACTION_ATTACH -> "Attach"
            ACTION_CLOSE -> "Close"
            ACTION_PREVIOUS -> "Previous page"
            ACTION_NEXT -> "Next page"
            ACTION_RESUME -> "Resume"
            COMPOSER_PLACEHOLDER -> "Ask about your documents…"
            CD_OPEN_CHATS -> "Open chats"
            LABEL_THOUGHT -> "Thought for a moment"
            LABEL_THINKING_LIVE -> "Thinking…"
            LABEL_THOUGHT_FOR -> "Thought for {0}"
            LABEL_WAITING_SUMMARY -> "Waiting for summary…"
            LABEL_NO_SUMMARY -> "No summary available."
            LABEL_TOOL_REQUEST -> "Request"
            LABEL_TOOL_RESULT -> "Result"
            LABEL_TOOL_WORKING -> "Working…"
            LABEL_TOOL_WAITING_REQUEST -> "Waiting for request…"
            CD_TOGGLE_REASONING -> "Toggle thought"
            CD_TOGGLE_TOOL -> "Toggle tool activity"
            CD_COPY_MESSAGE -> "Copy message"
            CD_ADD_CONTEXT -> "Add as context"
            CD_EDIT_MESSAGE -> "Edit message"
            CD_REGENERATE -> "Regenerate from this message"
            CD_FEATURES -> "Additional features"
            CD_ATTACH -> "Attach"
            CD_MODEL -> "Model and reasoning"
            LABEL_MODEL -> "Model"
            LABEL_REASONING -> "Reasoning"
            LABEL_REASONING_NONE -> "None"
            MODELS_EMPTY -> "No chat models are available."
            LABEL_WEB_SEARCH -> "Web search"
            LABEL_IMAGE_GEN -> "Image generate"
            LABEL_DEEP_RESEARCH -> "Deep research"
            LABEL_ATTACH -> "Add to this chat"
            LABEL_ATTACH_PHOTOS -> "Photos"
            LABEL_ATTACH_LOCAL -> "Local document"
            LABEL_ATTACH_LIBRARY -> "Uploaded files"
            LABEL_DOCUMENT_LIBRARY -> "Document library"
            LABEL_SEARCH_DOCUMENTS -> "Search documents"
            PLACEHOLDER_SEARCH_DOCUMENTS -> "Name or summary"
            LABEL_SESSION_IMAGES -> "Images"
            IMAGE_CONTEXT_HELP -> "Tap to pin as context"
            CD_UNPIN_IMAGE -> "Unpin image from context"
            LABEL_CONTEXT_USAGE -> "Context"
            CD_CONTEXT_USAGE -> "Show context usage"
            CD_SCROLL_TO_BOTTOM -> "Scroll to latest message"
            CD_LOADING_OLDER_MESSAGES -> "Loading earlier messages"
            LABEL_CONTEXT_MODEL -> "Model"
            LABEL_CONTEXT_TOKENS -> "Estimated tokens"
            LABEL_CONTEXT_USED -> "Context used"
            LABEL_CONTEXT_WINDOW -> "Context window"
            LABEL_CONTEXT_THRESHOLD -> "Warning threshold"
            LABEL_CONTEXT_TARGET -> "Compaction target"
            LABEL_SEARCH -> "Search"
            PLACEHOLDER_SEARCH_WORKSPACE -> "Name or summary"
            CD_WORKSPACE_SEARCH -> "Search workspace"
            CD_CARD_ACTIONS -> "Card actions"
            CD_GRID_VIEW -> "Grid view"
            CD_LIST_VIEW -> "List view"
            LABEL_FILTER_ALL -> "All"
            LABEL_FILTER_RECENT -> "Recent"
            LABEL_FILTER_SHARED -> "Shared"
            LABEL_SORT_UPDATED -> "Updated"
            LABEL_SORT_OPENED -> "Opened"
            LABEL_SORT_NAME -> "Name"
            LABEL_DOCUMENT_PREVIEW -> "Document preview"
            LABEL_DOCUMENT_IMAGE -> "Document page image"
            LABEL_APPEARANCE -> "Appearance"
            APPEARANCE_SECTION_BODY -> "Choose how Anreal looks and responds to motion preferences."
            LABEL_ACCOUNT_PREFERENCES -> "Account & preferences"
            LABEL_APPEARANCE_DESCRIPTION -> "Theme, color, motion"
            LABEL_USAGE_DESCRIPTION -> "Storage & tokens"
            LABEL_PERSONALIZATION_DESCRIPTION -> "Profile facts & projects"
            LABEL_HELP_FEEDBACK -> "Help & feedback"
            LABEL_HELP_FEEDBACK_DESCRIPTION -> "Docs & contact"
            LABEL_ABOUT -> "About"
            LABEL_ABOUT_DESCRIPTION -> "Anreal · Ratmo.co"
            LABEL_ACCOUNT_FOOTER -> "Anreal for Android · Presented by Ratmo.co"
            LABEL_THEME_CURRENT -> "Current: {0} · follows device dark/light."
            LABEL_DYNAMIC_COLOR_DESCRIPTION -> "Use wallpaper colors on Android 12+"
            LABEL_DYNAMIC_COLOR_HELPER -> "Harmonized with Anreal's seed"
            LABEL_REDUCE_MOTION_DESCRIPTION -> "Replace slides with a shorter fade"
            LABEL_REDUCE_MOTION_HELPER -> "Hides aurora, keeps layout"
            LABEL_REDUCE_TRANSPARENCY_DESCRIPTION -> "Use solid surfaces instead of frost"
            LABEL_REDUCE_TRANSPARENCY_HELPER -> "Glass becomes an opaque surface"
            LABEL_PREVIEW_WITH_FROST -> "Preview · with frost"
            LABEL_PREVIEW_GLASS_TOP_BAR -> "Glass top bar · thin frost"
            LABEL_PREVIEW_REDUCED -> "Preview · reduced"
            LABEL_PREVIEW_SURFACE_CONTAINER -> "Solid surface container"
            LABEL_API_STATUS -> "API status"
            STATUS_CHECKING -> "Checking…"
            STATUS_CONNECTED -> "Connected"
            STATUS_UNAVAILABLE -> "Unavailable"
            STATUS_UPLOAD_QUEUED -> "Queued"
            STATUS_UPLOAD_PROCESSING -> "Processing"
            STATUS_UPLOAD_UPLOADING -> "Uploading"
            STATUS_UPLOAD_FAILED -> "Failed"
            LABEL_THEME -> "Theme"
            LABEL_THEME_SYSTEM -> "System"
            LABEL_THEME_LIGHT -> "Light"
            LABEL_THEME_DARK -> "Dark"
            LABEL_DYNAMIC_COLOR -> "Use wallpaper colors"
            LABEL_REDUCE_MOTION -> "Reduce motion"
            LABEL_REDUCE_TRANSPARENCY -> "Reduce transparency"
            ATTACH_PHOTOS_BODY -> "Images from this device"
            ATTACH_LOCAL_BODY -> "PDF or image from this device"
            ATTACH_LIBRARY_BODY -> "Pick from your document library"
            ATTACH_LIBRARY_EMPTY -> "No documents are available to attach."
            TOAST_COPIED -> "Copied"
            FEATURE_UNAVAILABLE -> "Not configured on this server."
            LABEL_CHATS -> "Chats"
            LABEL_UNREAD -> "Unread"
            DIALOG_RUN_ACTIVE_TITLE -> "Chat already running"
            ACTION_WAIT -> "Wait"
            ACTION_RENAME -> "Rename"
            ACTION_DELETE -> "Delete"
            ACTION_SHARE -> "Share"
            ACTION_VIEW_PROJECT -> "View project"
            ACTION_VIEW_DOCUMENT -> "View document"
            ACTION_VIEW_PROJECT_DESCRIPTION -> "Open in chat with this project"
            ACTION_VIEW_DOCUMENT_DESCRIPTION -> "Open in chat with this document"
            ACTION_RENAME_DESCRIPTION -> "Edit the name and description"
            ACTION_SHARE_DESCRIPTION -> "Copy a link"
            ACTION_DELETE_DESCRIPTION -> "Permanently delete this item"
            LABEL_PROJECT_ACTIONS -> "Project actions"
            LABEL_DOCUMENT_ACTIONS -> "Document actions"
            LABEL_LOADED -> "loaded"
            ACTION_PULL_TO_REFRESH -> "pull to refresh"
            ACTION_DELETING -> "Deleting…"
            ACTION_CANCEL -> "Cancel"
            DIALOG_RENAME_TITLE -> "Rename chat"
            DIALOG_DELETE_TITLE -> "Delete chat"
            DIALOG_DELETE_BODY -> "This removes the conversation. Documents and preferences are not affected."
            DIALOG_DELETE_BODY_RUNNING -> "The running reply will stop."
            TOAST_CHAT_DELETED -> "Chat deleted"
            CD_SESSION_MENU -> "Chat actions"
            ERROR_TITLE_REQUIRED -> "Enter a name for this chat."
            LABEL_SESSION_TITLE -> "Name"
            TOOL_STATUS_WORKING -> "Working"
            TOOL_STATUS_DONE -> "Done"
            TOOL_STATUS_ERROR -> "Error"
            TOOL_RUNNING_FALLBACK -> "Running {0}"
            TOOL_FIND_DOCUMENTS -> "Finding documents"
            TOOL_SEARCH_DOCUMENT_PAGES -> "Searching document pages"
            TOOL_GET_DOCUMENT_NEXT_PAGE -> "Reading next page"
            TOOL_WEB_SEARCH -> "Searching the web"
            TOOL_WEB_FETCH -> "Fetching web page"
            TOOL_GENERATE_IMAGE -> "Generating image"
            TOOL_EDIT_IMAGE -> "Editing image"
            TOOL_VIEW_IMAGE -> "Viewing image"
            TOOL_DESCRIPTIVE_STATS -> "Computing statistics"
            TOOL_PEARSON -> "Computing correlation"
            TOOL_LINEAR_REGRESSION -> "Fitting regression"
            TOOL_PAGE_IMAGES -> "Inspecting page images"
            TOOL_CLARIFICATION -> "Asking for clarification"
            TOOL_RESOLVE_LIBRARY -> "Looking up library"
            TOOL_QUERY_DOCS -> "Reading library docs"
            ERROR_NO_ACTIVE_RUN -> "That run already finished. Send this as a new message."
            ERROR_INTERACTION_GONE -> "This interaction is no longer available."
            ERROR_INTERACTION_EXPIRED -> "This approval expired. Send a new message to continue."
            ERROR_INTERACTION_HANDLED -> "This interaction was already handled."
            ERROR_INTERACTION_UNAVAILABLE -> "Interaction policy is temporarily unavailable."
            ERROR_INTERACTION_INVALID -> "Interaction policy request is invalid."
            ERROR_SHARE_NOT_FOUND -> "This share link is no longer active."
            ERROR_NO_ACTIVE_SHARE -> "No active share link yet. Create one to copy it."
            ERROR_FORK_TARGET_NOT_FOUND -> "The chat to fork into was not found."
            ERROR_FORK_INVALID -> "This shared chat cannot be forked in its current form."
            ERROR_SHARE_UNAVAILABLE -> "Sharing is temporarily unavailable. Try again."
            ACTION_QUEUE -> "Queue"
            ACTION_SEND_NOW -> "Send now"
            ACTION_SEND_QUEUE -> "Send queue"
            ACTION_SEND_NEW_MESSAGE -> "Send new message"
            DIALOG_QUEUE_CONFLICT_TITLE -> "Send now or keep the queue?"
            DIALOG_QUEUE_CONFLICT_BODY -> "You have follow-ups waiting. Send the queue first, or send this new message and hold the queue."
            LABEL_QUEUED_COUNT -> "{0} queued"
            LABEL_EDITING -> "Editing…"
            CD_HIDE_QUEUE -> "Hide queue"
            CD_SHOW_QUEUE -> "Show queue"
            CD_REMOVE_QUEUED -> "Remove queued message"
            CD_EXPAND_QUEUE -> "Show all queued messages"
            LABEL_APP_NAME -> "Anreal"
            LABEL_WORKSPACE -> "Workspace"
            LABEL_ALL_CHATS -> "All chats"
            LABEL_PROJECTS -> "Projects"
            LABEL_DOCUMENTS -> "Documents"
            LABEL_IMAGES -> "Images"
            LABEL_SITES -> "Sites"
            LABEL_TASKS -> "Tasks"
            LABEL_SCHEDULES -> "Schedules"
            LABEL_ARTIFACTS -> "Artifacts"
            LABEL_ALL -> "All"
            LABEL_CAPTION -> "Caption"
            ARTIFACTS_OPEN_TASKS -> "Open in Tasks"
            ARTIFACTS_OPEN_SCHEDULES -> "Open in Schedules"
            ARTIFACTS_EMPTY -> "No artifacts yet"
            ARTIFACTS_NO_SCOPE -> "Open Workspace from a chat to browse its artifacts"
            LABEL_TITLE -> "Title"
            LABEL_PROMPT -> "Prompt"
            LABEL_RUN_AT -> "First run"
            LABEL_DUE_DATE -> "Due date"
            TASKS_NEW_TITLE -> "New task"
            SCHEDULES_NEW_TITLE -> "New schedule"
            TASKS_EDIT_TITLE -> "Edit task"
            TASKS_SUBTASKS_TITLE -> "Subtasks"
            TASKS_ADD_SUBTASK -> "Add subtask"
            SITES_EMPTY -> "No sites in this scope yet"
            SITES_NO_SCOPE -> "Open Workspace from a chat to browse its sites"
            TASKS_EMPTY -> "No tasks yet"
            TASKS_NO_SCOPE -> "Open Workspace from a chat to manage its tasks"
            SCHEDULES_EMPTY -> "No schedules yet"
            SCHEDULES_NO_SCOPE -> "Open Workspace from a chat to manage its schedules"
            ERROR_DUE_DATE_INVALID -> "Use a full date-time, e.g. 2026-09-30T10:00:00+07:00"
            ERROR_PROMPT_REQUIRED -> "Describe what the schedule should do."
            ERROR_NOTHING_TO_UPDATE -> "Nothing to update."
            LABEL_RECENT_PROJECTS -> "Recent projects"
            LABEL_PROJECT_CHAT_TITLE -> "{0} · {1}"
            LABEL_TODAY -> "Today"
            LABEL_YESTERDAY -> "Yesterday"
            LABEL_EARLIER -> "Earlier"
            CD_OPEN_DOCUMENTS -> "Session documents"
            LABEL_ACTIVE_DOCUMENTS -> "Active documents"
            LABEL_CITED_DOCUMENTS -> "Cited documents"
            LABEL_DOCUMENTS_NONE -> "None yet"
            LABEL_DOCUMENTS_SUMMARY -> "{0} active · {1} cited"
            LABEL_CITATION_COUNT -> "{0} citations"
            CD_REMOVE_DOCUMENT -> "Remove from this chat"
            DOCUMENTS_EMPTY_BODY -> "Attach a file or pick from your library to ground this chat."
            ACTION_SETTINGS -> "Settings"
            ACTION_LOG_OUT -> "Log out"
            ACTION_LOGGING_OUT -> "Signing out…"
            DIALOG_SIGN_OUT_TITLE -> "Log out of Anreal?"
            DIALOG_SIGN_OUT_BODY -> "This signs you out on this device. Your chats stay saved."
            CD_ACCOUNT_MENU -> "Account menu"
            CD_OPEN_ACCOUNT -> "Open account"
            CD_BACK -> "Back"
            CD_SCROLL_TABS_BACK -> "Scroll tabs left"
            CD_SCROLL_TABS_FORWARD -> "Scroll tabs right"
            LABEL_ACCOUNT -> "Account"
            LABEL_USAGE -> "Usage"
            LABEL_PERSONALIZATION -> "Personalization"
            ACCOUNT_SECTION_BODY -> "Profile details for this workspace."
            ACCOUNT_EMAIL_EMPTY -> "No email on this account."
            USAGE_SECTION_BODY -> "Storage, tokens, and how you use models and reasoning."
            USAGE_EMPTY -> "No chat requests yet. Model and reasoning mix will appear here."
            PERSONALIZATION_SECTION_BODY ->
                "What the assistant knows about you, built automatically from your chats. Reset anytime to start fresh."
            PERSONALIZATION_EMPTY -> "No profile yet. It builds automatically from your chats."
            LABEL_STORAGE -> "Storage"
            LABEL_REQUESTS -> "Requests"
            LABEL_TOTAL_TOKENS -> "Total tokens"
            LABEL_INPUT_TOKENS -> "Input"
            LABEL_OUTPUT_TOKENS -> "Output"
            LABEL_CACHED_TOKENS -> "Cached input"
            LABEL_BY_MODEL -> "By model"
            LABEL_BY_REASONING -> "By reasoning"
            LABEL_PROFILE_FACTS -> "Your profile"
            LABEL_PROJECT_PROFILES -> "Project profiles"
            ACTION_RESET -> "Reset"
            ACTION_RESETTING -> "Resetting…"
            DIALOG_RESET_PROFILE_TITLE -> "Reset personalization?"
            DIALOG_RESET_PROFILE_BODY ->
                "This permanently removes the learned profile. New chats can build it again."
            TOAST_PROFILE_RESET -> "Personalization reset"
            ACTION_NEW_PROJECT -> "New project"
            ACTION_CREATE -> "Create"
            LABEL_DESCRIPTION -> "Description"
            LABEL_IMAGE -> "Image"
            PROJECTS_EMPTY -> "No projects yet. Create one to keep related chats and sources together."
            PROJECT_DESCRIPTION_EMPTY -> "No description"
            DOCUMENTS_LIBRARY_EMPTY -> "No documents in your library yet. Attach one from a chat."
            IMAGES_EMPTY -> "No generated or uploaded images yet."
            DIALOG_DELETE_WORKSPACE_TITLE -> "Delete item?"
            DIALOG_DELETE_WORKSPACE_BODY -> "Delete {0}? This cannot be undone."
            ERROR_FILE_TOO_LARGE -> "Files must be 10 MB or smaller."
            ERROR_FILE_READ -> "Could not read that file."
            TOAST_UPLOAD_COMPLETE -> "Upload started. It will appear when processing is ready."
            APPROVAL_TITLE -> "Approval required"
            CLARIFICATION_TITLE -> "A little more detail"
            ACTION_ALLOW_ONCE -> "Allow once"
            ACTION_ALLOW_SESSION -> "Allow for session"
            ACTION_REJECT -> "Reject"
            ACTION_SUBMIT -> "Submit"
            IMAGE_OVERRIDE_TITLE -> "Image options"
            DIALOG_SHARE_TITLE -> "Share this chat"
            DIALOG_SHARE_BODY -> "Anyone with the link can read a frozen copy. New messages stay private."
            DIALOG_SHARE_NO_LINK -> "No active link yet. Create one to share a frozen copy."
            ACTION_CREATE_LINK -> "Create link"
            ACTION_CREATING_LINK -> "Creating link…"
            ACTION_COPY_LINK -> "Copy link"
            ACTION_DEACTIVATE_LINKS -> "Deactivate all links"
            ACTION_DEACTIVATING_LINKS -> "Deactivating…"
            DIALOG_DEACTIVATE_SHARES_TITLE -> "Deactivate all share links?"
            DIALOG_DEACTIVATE_SHARES_BODY -> "Every link for this chat stops working. This cannot be undone."
            TOAST_SHARE_LINK_COPIED -> "Share link copied"
            TOAST_SHARES_DEACTIVATED -> "All share links deactivated"
            TOAST_SHARE_CREATED -> "Share link created"
            CD_SHARE_CHAT -> "Share chat"
            SHARED_CHAT_TITLE -> "Shared chat"
            SHARED_CHAT_SUBTITLE -> "Read-only copy"
            SHARED_CHAT_EMPTY -> "This shared copy has no messages to show."
            SHARED_CHAT_SIGN_IN_CTA -> "Sign in to continue this chat in your workspace"
            SHARED_CHAT_FORKING -> "Copying to your workspace…"
            SHARED_CHAT_FORK_CHIP -> "Continue as your own copy"
            SHARED_CHAT_GATE_BODY -> "Log in or create an account to continue this shared chat as your own copy."
            LABEL_SKILLS -> "Skills"
            LABEL_MCP -> "MCP servers"
            CD_MANAGE_SKILLS -> "Manage skills"
            CD_MANAGE_MCP -> "Manage MCP servers"
            SKILLS_ON -> "Skills on — the agent follows your enabled skills"
            SKILLS_OFF -> "Skills off for this chat"
            SKILLS_EMPTY -> "No skills yet — open Skills to write the first one"
            MCP_ON -> "MCP on — the agent can use your connected servers"
            MCP_OFF -> "MCP off for this chat"
            MCP_EMPTY -> "No servers yet — open MCP to connect the first one"
            SKILLS_LIST_EMPTY_TITLE -> "No skills yet"
            SKILLS_LIST_EMPTY_BODY -> "Write the first one to teach the agent a reusable skill."
            SKILLS_LOAD_ERROR -> "Could not load skills"
            MCP_LIST_EMPTY_TITLE -> "No servers yet"
            MCP_LIST_EMPTY_BODY -> "Connect the first one to give the agent tools."
            MCP_LOAD_ERROR -> "Could not load MCP servers"
            ACTION_NEW -> "New"
            ACTION_SAVE -> "Save"
            ACTION_SAVING -> "Saving…"
            ACTION_UPLOAD_MD -> "Upload .md"
            ACTION_ADD_HEADER -> "Add header"
            SKILL_STATUS_DRAFT -> "Draft — review in the editor before enabling"
            SKILL_STATUS_INVALID -> "Invalid — edit to fix"
            SKILL_EDITOR_NEW_TITLE -> "New skill"
            SKILL_EDITOR_EDIT_TITLE -> "Edit skill"
            SKILL_NAME_PLACEHOLDER -> "e.g. release-notes"
            SKILL_DESCRIPTION_PLACEHOLDER -> "One line the agent uses to decide fit."
            SKILL_BODY_LABEL -> "SKILL.md"
            SKILL_BODY_PLACEHOLDER -> "Starts with --- frontmatter."
            DIALOG_DELETE_SKILL_TITLE -> "Delete skill?"
            DIALOG_DELETE_SKILL_BODY -> "Delete “{0}”? This cannot be undone."
            CD_EDIT_SKILL -> "Edit skill"
            CD_DELETE_SKILL -> "Delete skill"
            CD_TOGGLE_SKILL -> "Toggle skill"
            MCP_EDITOR_NEW_TITLE -> "New MCP server"
            MCP_EDITOR_EDIT_TITLE -> "Edit MCP server"
            MCP_URL_LABEL -> "URL"
            MCP_URL_PLACEHOLDER -> "https://mcp.example.com/mcp"
            MCP_AUTH_LABEL -> "Auth"
            MCP_AUTH_NONE -> "None"
            MCP_AUTH_BEARER -> "Bearer token"
            MCP_TOKEN_LABEL -> "Token"
            MCP_TOKEN_PLACEHOLDER -> "Paste token"
            MCP_TOKEN_KEEP -> "Leave empty to keep the saved token."
            MCP_HEADERS_LABEL -> "Headers"
            MCP_TEST_ACTION -> "Test"
            MCP_TESTING_ACTION -> "Testing…"
            MCP_RETEST_ACTION -> "Re-test"
            MCP_TEST_FIRST -> "Test the connection first before saving."
            MCP_URL_RETEST -> "URL changed — re-test before saving."
            MCP_TOOLS_MIN -> "Allow at least one tool."
            MCP_TOOLS_TITLE -> "Tools ({0}/{1})"
            MCP_TOOLS_COUNT -> "{0} tools"
            MCP_SERVER_UNTESTED -> "{0} tools · untested — test in the editor to activate"
            MCP_TEST_OK -> "Connected — select the tools to allow."
            DIALOG_DELETE_MCP_TITLE -> "Delete server?"
            DIALOG_DELETE_MCP_BODY -> "Delete “{0}”? This cannot be undone."
            CD_EDIT_SERVER -> "Edit server"
            CD_DELETE_SERVER -> "Delete server"
            CD_TOGGLE_SERVER -> "Toggle server"
            CD_REMOVE_HEADER -> "Remove header"
            LABEL_HEADER_NAME -> "Header"
            LABEL_HEADER_VALUE -> "Value"
            SITE_PREVIEW_ACTION -> "Lihat pratinjau"
            SITE_DOWNLOAD_ACTION -> "Unduh zip"
            SITE_RETRY_ACTION -> "Coba lagi"
            SITE_HIDE -> "Hide"
            SITE_SHOW -> "Show"
            SITE_ROLLBACK -> "Rollback"
            SITE_VERSION_STABLE -> "v{0} (stabil)"
            SITE_VERSION_FAILED -> "v{0} • gagal"
            SITE_VERSION_PLAIN -> "v{0}"
            SITE_STEP_STARTING -> "Menyiapkan"
            SITE_STEP_PLANNING -> "Menyusun brief"
            SITE_STEP_BUILDING -> "Membangun halaman"
            SITE_STEP_BUNDLING -> "Build production"
            SITE_STEP_PREVIEW -> "Menyiapkan pratinjau"
            SITE_STEP_READY -> "Siap"
            SITE_PREVIEW_TITLE -> "Site preview"
            SITE_PREVIEW_UNAVAILABLE -> "Preview is not available on this device yet."
            SITE_DOWNLOAD_SAVED -> "Site zip saved."
            SITE_DOWNLOAD_FAILED -> "Could not save that file."
            SITE_OPEN_CHAT -> "Open chat"
            SITE_CONTINUE -> "Continue"
            SITE_CONTINUE_DRAFT -> "Lanjutkan site ini (site {0})"
            else -> key
        }
    }
}

fun UiText.asString(): String {
    return when (this) {
        is UiText.DynamicString -> value
        is UiText.StringResource -> interpolate(AnrealCopy.get(key), args)
    }
}

internal fun interpolate(template: String, args: List<String>): String {
    return args.foldIndexed(template) { index, acc, arg ->
        acc.replace("{$index}", arg)
    }
}
