package co.ratmo.anreal.core.presentation

object AnrealCopy {
    const val ERROR_NO_INTERNET = "error_no_internet"
    const val ERROR_UNAUTHORIZED = "error_unauthorized"
    const val ERROR_FORBIDDEN = "error_forbidden"
    const val ERROR_NOT_FOUND = "error_not_found"
    const val ERROR_TIMEOUT = "error_timeout"
    const val ERROR_CONFLICT = "error_conflict"
    const val ERROR_TOO_MANY_REQUESTS = "error_too_many_requests"
    const val ERROR_SERVER = "error_server"
    const val ERROR_UNKNOWN = "error_unknown"
    const val ERROR_DISK_FULL = "error_disk_full"
    const val ERROR_INVALID_EMAIL = "error_invalid_email"
    const val ERROR_PASSWORD_TOO_SHORT = "error_password_too_short"
    const val ERROR_PASSWORD_MISMATCH = "error_password_mismatch"
    const val ERROR_NAME_REQUIRED = "error_name_required"
    const val ERROR_INVALID_CREDENTIALS = "error_invalid_credentials"
    const val ERROR_EMAIL_TAKEN = "error_email_taken"
    const val ERROR_SIGN_IN_FAILED = "error_sign_in_failed"
    const val ERROR_SIGN_UP_FAILED = "error_sign_up_failed"

    const val LABEL_EMAIL = "label_email"
    const val LABEL_PASSWORD = "label_password"
    const val LABEL_NAME = "label_name"
    const val LABEL_CONFIRM_PASSWORD = "label_confirm_password"
    const val ACTION_CONTINUE = "action_continue"
    const val ACTION_SIGNING_IN = "action_signing_in"
    const val ACTION_CREATE_ACCOUNT = "action_create_account"
    const val ACTION_CREATING_ACCOUNT = "action_creating_account"
    const val ACTION_RETRY = "action_retry"
    const val ACTION_SHOW_PASSWORD = "action_show_password"
    const val ACTION_HIDE_PASSWORD = "action_hide_password"
    const val STATUS_LOADING = "status_loading"
    const val ERROR_RUN_ACTIVE = "error_run_active"
    const val CHAT_EMPTY_TITLE = "chat_empty_title"
    const val CHAT_EMPTY_BODY = "chat_empty_body"
    const val CHAT_SESSIONS_EMPTY_TITLE = "chat_sessions_empty_title"
    const val CHAT_SESSIONS_EMPTY_BODY = "chat_sessions_empty_body"
    const val ACTION_NEW_CHAT = "action_new_chat"
    const val ACTION_SEND = "action_send"
    const val ACTION_STOP = "action_stop"
    const val ACTION_RESUME = "action_resume"
    const val COMPOSER_PLACEHOLDER = "composer_placeholder"
    const val LABEL_THOUGHT = "label_thought"
    const val CD_COPY_MESSAGE = "cd_copy_message"
    const val CD_ADD_CONTEXT = "cd_add_context"
    const val CD_EDIT_MESSAGE = "cd_edit_message"
    const val CD_REGENERATE = "cd_regenerate"
    const val CD_FEATURES = "cd_features"
    const val CD_ATTACH = "cd_attach"
    const val CD_MODEL = "cd_model"
    const val LABEL_MODEL = "label_model"
    const val LABEL_REASONING = "label_reasoning"
    const val LABEL_REASONING_NONE = "label_reasoning_none"
    const val LABEL_WEB_SEARCH = "label_web_search"
    const val LABEL_IMAGE_GEN = "label_image_gen"
    const val LABEL_ATTACH = "label_attach"
    const val LABEL_ATTACH_PHOTOS = "label_attach_photos"
    const val LABEL_ATTACH_LOCAL = "label_attach_local"
    const val LABEL_ATTACH_LIBRARY = "label_attach_library"
    const val ATTACH_PHOTOS_BODY = "attach_photos_body"
    const val ATTACH_LOCAL_BODY = "attach_local_body"
    const val ATTACH_LIBRARY_BODY = "attach_library_body"
    const val ATTACH_LIBRARY_EMPTY = "attach_library_empty"
    const val TOAST_COPIED = "toast_copied"
    const val TOAST_REGENERATE_SOON = "toast_regenerate_soon"
    const val TOAST_PICKER_SOON = "toast_picker_soon"
    const val FEATURE_UNAVAILABLE = "feature_unavailable"
    const val CD_OPEN_CHATS = "cd_open_chats"
    const val LABEL_CHATS = "label_chats"
    const val LABEL_UNREAD = "label_unread"
    const val DIALOG_RUN_ACTIVE_TITLE = "dialog_run_active_title"
    const val ACTION_WAIT = "action_wait"
    const val ACTION_RENAME = "action_rename"
    const val ACTION_DELETE = "action_delete"
    const val ACTION_DELETING = "action_deleting"
    const val ACTION_CANCEL = "action_cancel"
    const val DIALOG_RENAME_TITLE = "dialog_rename_title"
    const val DIALOG_DELETE_TITLE = "dialog_delete_title"
    const val DIALOG_DELETE_BODY = "dialog_delete_body"
    const val DIALOG_DELETE_BODY_RUNNING = "dialog_delete_body_running"
    const val TOAST_CHAT_DELETED = "toast_chat_deleted"
    const val CD_SESSION_MENU = "cd_session_menu"
    const val ERROR_TITLE_REQUIRED = "error_title_required"
    const val LABEL_SESSION_TITLE = "label_session_title"
    const val TOOL_STATUS_WORKING = "tool_status_working"
    const val TOOL_STATUS_DONE = "tool_status_done"
    const val TOOL_STATUS_ERROR = "tool_status_error"
    const val TOOL_RUNNING_FALLBACK = "tool_running_fallback"
    const val TOOL_FIND_DOCUMENTS = "tool_find_documents"
    const val TOOL_SEARCH_DOCUMENT_PAGES = "tool_search_document_pages"
    const val TOOL_GET_DOCUMENT_NEXT_PAGE = "tool_get_document_next_page"
    const val TOOL_WEB_SEARCH = "tool_web_search"
    const val TOOL_WEB_FETCH = "tool_web_fetch"
    const val TOOL_GENERATE_IMAGE = "tool_generate_image"
    const val TOOL_EDIT_IMAGE = "tool_edit_image"
    const val TOOL_VIEW_IMAGE = "tool_view_image"
    const val TOOL_DESCRIPTIVE_STATS = "tool_descriptive_stats"
    const val ERROR_NO_ACTIVE_RUN = "error_no_active_run"
    const val ACTION_QUEUE = "action_queue"
    const val ACTION_SEND_NOW = "action_send_now"
    const val ACTION_SEND_QUEUE = "action_send_queue"
    const val ACTION_SEND_NEW_MESSAGE = "action_send_new_message"
    const val DIALOG_QUEUE_CONFLICT_TITLE = "dialog_queue_conflict_title"
    const val DIALOG_QUEUE_CONFLICT_BODY = "dialog_queue_conflict_body"
    const val LABEL_QUEUED_COUNT = "label_queued_count"
    const val LABEL_EDITING = "label_editing"
    const val CD_HIDE_QUEUE = "cd_hide_queue"
    const val CD_SHOW_QUEUE = "cd_show_queue"
    const val CD_REMOVE_QUEUED = "cd_remove_queued"
    const val CD_EXPAND_QUEUE = "cd_expand_queue"
    const val LABEL_APP_NAME = "label_app_name"
    const val LABEL_WORKSPACE = "label_workspace"
    const val LABEL_ALL_CHATS = "label_all_chats"
    const val LABEL_PROJECTS = "label_projects"
    const val LABEL_DOCUMENTS = "label_documents"
    const val LABEL_IMAGES = "label_images"
    const val LABEL_RECENT_PROJECTS = "label_recent_projects"
    const val LABEL_TODAY = "label_today"
    const val LABEL_YESTERDAY = "label_yesterday"
    const val LABEL_EARLIER = "label_earlier"
    const val CD_OPEN_DOCUMENTS = "cd_open_documents"
    const val LABEL_ACTIVE_DOCUMENTS = "label_active_documents"
    const val LABEL_CITED_DOCUMENTS = "label_cited_documents"
    const val LABEL_DOCUMENTS_NONE = "label_documents_none"
    const val LABEL_DOCUMENTS_SUMMARY = "label_documents_summary"
    const val LABEL_CITATION_COUNT = "label_citation_count"
    const val CD_REMOVE_DOCUMENT = "cd_remove_document"
    const val DOCUMENTS_EMPTY_BODY = "documents_empty_body"
    const val ACTION_SETTINGS = "action_settings"
    const val ACTION_LOG_OUT = "action_log_out"
    const val ACTION_LOGGING_OUT = "action_logging_out"
    const val CD_ACCOUNT_MENU = "cd_account_menu"
    const val CD_OPEN_ACCOUNT = "cd_open_account"
    const val CD_BACK = "cd_back"
    const val LABEL_ACCOUNT = "label_account"
    const val LABEL_USAGE = "label_usage"
    const val LABEL_PERSONALIZATION = "label_personalization"
    const val ACCOUNT_SECTION_BODY = "account_section_body"
    const val ACCOUNT_EMAIL_EMPTY = "account_email_empty"
    const val USAGE_SECTION_BODY = "usage_section_body"
    const val USAGE_EMPTY = "usage_empty"
    const val PERSONALIZATION_SECTION_BODY = "personalization_section_body"
    const val PERSONALIZATION_EMPTY = "personalization_empty"
    const val TOAST_PROJECTS_SOON = "toast_projects_soon"
    const val TOAST_DOCUMENTS_SOON = "toast_documents_soon"
    const val TOAST_IMAGES_SOON = "toast_images_soon"

    fun get(key: String): String {
        return when (key) {
            ERROR_NO_INTERNET -> "Check your connection and try again."
            ERROR_UNAUTHORIZED -> "Sign in to continue."
            ERROR_FORBIDDEN -> "You don't have access to that."
            ERROR_NOT_FOUND -> "We couldn't find that."
            ERROR_TIMEOUT -> "That took too long. Try again."
            ERROR_CONFLICT -> "That conflicts with the current state. Try again."
            ERROR_TOO_MANY_REQUESTS -> "Too many attempts. Wait a moment and try again."
            ERROR_SERVER -> "The server had a problem. Try again."
            ERROR_UNKNOWN -> "Something went wrong. Try again."
            ERROR_DISK_FULL -> "Not enough storage to finish that."
            ERROR_INVALID_EMAIL -> "Enter a valid email address."
            ERROR_PASSWORD_TOO_SHORT -> "Password must be at least 8 characters."
            ERROR_PASSWORD_MISMATCH -> "Passwords do not match."
            ERROR_NAME_REQUIRED -> "Name is required."
            ERROR_INVALID_CREDENTIALS -> "Invalid email or password."
            ERROR_EMAIL_TAKEN -> "An account with that email already exists."
            ERROR_SIGN_IN_FAILED -> "Could not sign in. Check your connection and try again."
            ERROR_SIGN_UP_FAILED -> "Could not create an account. Try again."
            LABEL_EMAIL -> "Email"
            LABEL_PASSWORD -> "Password"
            LABEL_NAME -> "Name"
            LABEL_CONFIRM_PASSWORD -> "Confirm password"
            ACTION_CONTINUE -> "Continue"
            ACTION_SIGNING_IN -> "Signing in…"
            ACTION_CREATE_ACCOUNT -> "Create account"
            ACTION_CREATING_ACCOUNT -> "Creating account…"
            ACTION_RETRY -> "Retry"
            ACTION_SHOW_PASSWORD -> "Show password"
            ACTION_HIDE_PASSWORD -> "Hide password"
            STATUS_LOADING -> "Loading"
            ERROR_RUN_ACTIVE -> "This chat is already running. Resume it or wait for it to finish."
            CHAT_EMPTY_TITLE -> "Ask anything about your documents"
            CHAT_EMPTY_BODY -> "Upload a PDF or image, then ask questions."
            CHAT_SESSIONS_EMPTY_TITLE -> "No chats yet"
            CHAT_SESSIONS_EMPTY_BODY -> "Start a conversation about your documents."
            ACTION_NEW_CHAT -> "New chat"
            ACTION_SEND -> "Send"
            ACTION_STOP -> "Stop"
            ACTION_RESUME -> "Resume"
            COMPOSER_PLACEHOLDER -> "Ask about your documents…"
            CD_OPEN_CHATS -> "Open chats"
            LABEL_THOUGHT -> "Thought for a moment"
            CD_COPY_MESSAGE -> "Copy message"
            CD_ADD_CONTEXT -> "Add as context"
            CD_EDIT_MESSAGE -> "Edit message"
            CD_REGENERATE -> "Regenerate from this message"
            CD_FEATURES -> "Additional features"
            CD_ATTACH -> "Attach"
            CD_MODEL -> "Model and reasoning"
            LABEL_MODEL -> "Model"
            LABEL_REASONING -> "Reasoning"
            LABEL_REASONING_NONE -> "None"
            LABEL_WEB_SEARCH -> "Web search"
            LABEL_IMAGE_GEN -> "Image generate"
            LABEL_ATTACH -> "Add to this chat"
            LABEL_ATTACH_PHOTOS -> "Photos"
            LABEL_ATTACH_LOCAL -> "Local document"
            LABEL_ATTACH_LIBRARY -> "Uploaded files"
            ATTACH_PHOTOS_BODY -> "Images from this device"
            ATTACH_LOCAL_BODY -> "PDF or image from this device"
            ATTACH_LIBRARY_BODY -> "Pick from your document library"
            ATTACH_LIBRARY_EMPTY -> "No uploaded files yet. Documents will appear here after the library ships."
            TOAST_COPIED -> "Copied"
            TOAST_REGENERATE_SOON -> "Regenerate will land with session truncate."
            TOAST_PICKER_SOON -> "File picking ships with the documents library."
            FEATURE_UNAVAILABLE -> "Not configured on this server."
            LABEL_CHATS -> "Chats"
            LABEL_UNREAD -> "Unread"
            DIALOG_RUN_ACTIVE_TITLE -> "Chat already running"
            ACTION_WAIT -> "Wait"
            ACTION_RENAME -> "Rename"
            ACTION_DELETE -> "Delete"
            ACTION_DELETING -> "Deleting…"
            ACTION_CANCEL -> "Cancel"
            DIALOG_RENAME_TITLE -> "Rename chat"
            DIALOG_DELETE_TITLE -> "Delete chat"
            DIALOG_DELETE_BODY -> "This removes the conversation. Documents and preferences are not affected."
            DIALOG_DELETE_BODY_RUNNING -> "The running reply will stop."
            TOAST_CHAT_DELETED -> "Chat deleted"
            CD_SESSION_MENU -> "Chat actions"
            ERROR_TITLE_REQUIRED -> "Enter a name for this chat."
            LABEL_SESSION_TITLE -> "Name"
            TOOL_STATUS_WORKING -> "Working"
            TOOL_STATUS_DONE -> "Done"
            TOOL_STATUS_ERROR -> "Error"
            TOOL_RUNNING_FALLBACK -> "Running {0}"
            TOOL_FIND_DOCUMENTS -> "Finding documents"
            TOOL_SEARCH_DOCUMENT_PAGES -> "Searching document pages"
            TOOL_GET_DOCUMENT_NEXT_PAGE -> "Reading next page"
            TOOL_WEB_SEARCH -> "Searching the web"
            TOOL_WEB_FETCH -> "Fetching web page"
            TOOL_GENERATE_IMAGE -> "Generating image"
            TOOL_EDIT_IMAGE -> "Editing image"
            TOOL_VIEW_IMAGE -> "Viewing image"
            TOOL_DESCRIPTIVE_STATS -> "Computing statistics"
            ERROR_NO_ACTIVE_RUN -> "That run already finished. Send this as a new message."
            ACTION_QUEUE -> "Queue"
            ACTION_SEND_NOW -> "Send now"
            ACTION_SEND_QUEUE -> "Send queue"
            ACTION_SEND_NEW_MESSAGE -> "Send new message"
            DIALOG_QUEUE_CONFLICT_TITLE -> "Send now or keep the queue?"
            DIALOG_QUEUE_CONFLICT_BODY -> "You have follow-ups waiting. Send the queue first, or send this new message and hold the queue."
            LABEL_QUEUED_COUNT -> "{0} queued"
            LABEL_EDITING -> "Editing…"
            CD_HIDE_QUEUE -> "Hide queue"
            CD_SHOW_QUEUE -> "Show queue"
            CD_REMOVE_QUEUED -> "Remove queued message"
            CD_EXPAND_QUEUE -> "Show all queued messages"
            LABEL_APP_NAME -> "Anreal"
            LABEL_WORKSPACE -> "Workspace"
            LABEL_ALL_CHATS -> "All chats"
            LABEL_PROJECTS -> "Projects"
            LABEL_DOCUMENTS -> "Documents"
            LABEL_IMAGES -> "Images"
            LABEL_RECENT_PROJECTS -> "Recent projects"
            LABEL_TODAY -> "Today"
            LABEL_YESTERDAY -> "Yesterday"
            LABEL_EARLIER -> "Earlier"
            CD_OPEN_DOCUMENTS -> "Session documents"
            LABEL_ACTIVE_DOCUMENTS -> "Active documents"
            LABEL_CITED_DOCUMENTS -> "Cited documents"
            LABEL_DOCUMENTS_NONE -> "None yet"
            LABEL_DOCUMENTS_SUMMARY -> "{0} active · {1} cited"
            LABEL_CITATION_COUNT -> "{0} citations"
            CD_REMOVE_DOCUMENT -> "Remove from this chat"
            DOCUMENTS_EMPTY_BODY -> "Attach a file or pick from your library to ground this chat."
            ACTION_SETTINGS -> "Settings"
            ACTION_LOG_OUT -> "Log out"
            ACTION_LOGGING_OUT -> "Signing out…"
            CD_ACCOUNT_MENU -> "Account menu"
            CD_OPEN_ACCOUNT -> "Open account"
            CD_BACK -> "Back"
            LABEL_ACCOUNT -> "Account"
            LABEL_USAGE -> "Usage"
            LABEL_PERSONALIZATION -> "Personalization"
            ACCOUNT_SECTION_BODY -> "Profile details for this workspace."
            ACCOUNT_EMAIL_EMPTY -> "No email on this account."
            USAGE_SECTION_BODY -> "Storage, tokens, and how you use models and reasoning."
            USAGE_EMPTY -> "No chat requests yet. Model and reasoning mix will appear here."
            PERSONALIZATION_SECTION_BODY ->
                "What the assistant knows about you, built automatically from your chats. Reset anytime to start fresh."
            PERSONALIZATION_EMPTY -> "No profile yet. It builds automatically from your chats."
            TOAST_PROJECTS_SOON -> "Projects will land with the workspace browser."
            TOAST_DOCUMENTS_SOON -> "The document library will land next."
            TOAST_IMAGES_SOON -> "The image gallery will land next."
            else -> key
        }
    }
}

fun UiText.asString(): String {
    return when (this) {
        is UiText.DynamicString -> value
        is UiText.StringResource -> interpolate(AnrealCopy.get(key), args)
    }
}

internal fun interpolate(template: String, args: List<String>): String {
    return args.foldIndexed(template) { index, acc, arg ->
        acc.replace("{$index}", arg)
    }
}
