package co.ratmo.anreal.core.presentation

object AnrealCopy {
    const val ERROR_NO_INTERNET = "error_no_internet"
    const val ERROR_UNAUTHORIZED = "error_unauthorized"
    const val ERROR_FORBIDDEN = "error_forbidden"
    const val ERROR_NOT_FOUND = "error_not_found"
    const val ERROR_TIMEOUT = "error_timeout"
    const val ERROR_CONFLICT = "error_conflict"
    const val ERROR_TOO_MANY_REQUESTS = "error_too_many_requests"
    const val ERROR_SERVER = "error_server"
    const val ERROR_UNKNOWN = "error_unknown"
    const val ERROR_DISK_FULL = "error_disk_full"
    const val ERROR_INVALID_EMAIL = "error_invalid_email"
    const val ERROR_PASSWORD_TOO_SHORT = "error_password_too_short"
    const val ERROR_PASSWORD_MISMATCH = "error_password_mismatch"
    const val ERROR_NAME_REQUIRED = "error_name_required"
    const val ERROR_INVALID_CREDENTIALS = "error_invalid_credentials"
    const val ERROR_EMAIL_TAKEN = "error_email_taken"
    const val ERROR_SIGN_IN_FAILED = "error_sign_in_failed"
    const val ERROR_SIGN_UP_FAILED = "error_sign_up_failed"
    const val ERROR_STORAGE_QUOTA = "error_storage_quota"
    const val ERROR_DOCUMENT_INGEST = "error_document_ingest"
    const val ERROR_IMAGE_LOAD = "error_image_load"
    const val ERROR_REGENERATE_UNAVAILABLE = "error_regenerate_unavailable"
    const val ERROR_SESSION_STALE = "error_session_stale"

    const val LABEL_EMAIL = "label_email"
    const val LABEL_PASSWORD = "label_password"
    const val LABEL_NAME = "label_name"
    const val LABEL_CONFIRM_PASSWORD = "label_confirm_password"
    const val ACTION_CONTINUE = "action_continue"
    const val ACTION_LOAD_MORE = "action_load_more"
    const val ACTION_ATTACH = "action_attach"
    const val ACTION_CLOSE = "action_close"
    const val ACTION_PREVIOUS = "action_previous"
    const val ACTION_NEXT = "action_next"
    const val ACTION_SIGNING_IN = "action_signing_in"
    const val ACTION_CREATE_ACCOUNT = "action_create_account"
    const val ACTION_CREATING_ACCOUNT = "action_creating_account"
    const val ACTION_SIGN_IN = "action_sign_in"
    const val AUTH_HAVE_ACCOUNT = "auth_have_account"
    const val AUTH_NEW_HERE = "auth_new_here"
    const val LOGIN_TITLE = "login_title"
    const val LOGIN_SUBTITLE = "login_subtitle"
    const val REGISTER_TITLE = "register_title"
    const val REGISTER_SUBTITLE = "register_subtitle"
    const val PLACEHOLDER_EMAIL = "placeholder_email"
    const val PLACEHOLDER_PASSWORD = "placeholder_password"
    const val PLACEHOLDER_NAME = "placeholder_name"
    const val PLACEHOLDER_PASSWORD_NEW = "placeholder_password_new"
    const val PLACEHOLDER_PASSWORD_REPEAT = "placeholder_password_repeat"
    const val SPLASH_VERSION = "splash_version"
    const val SPLASH_CREDIT = "splash_credit"
    const val CD_APP_MARK = "cd_app_mark"
    const val BOARDING_DOCUMENTS_TITLE = "boarding_documents_title"
    const val BOARDING_DOCUMENTS_BODY = "boarding_documents_body"
    const val BOARDING_WEB_TITLE = "boarding_web_title"
    const val BOARDING_WEB_BODY = "boarding_web_body"
    const val BOARDING_IMAGES_TITLE = "boarding_images_title"
    const val BOARDING_IMAGES_BODY = "boarding_images_body"
    const val CD_BOARDING_PAGE = "cd_boarding_page"
    const val BOARDING_USER_PROMPT = "boarding_user_prompt"
    const val BOARDING_ASSISTANT_REPLY = "boarding_assistant_reply"
    const val BOARDING_CITATION = "boarding_citation"
    const val BOARDING_WEB_TOOL = "boarding_web_tool"
    const val BOARDING_WEB_SOURCE = "boarding_web_source"
    const val BOARDING_IMAGE_CAPTION = "boarding_image_caption"
    const val BOARDING_TAGLINE = "boarding_tagline"
    const val BOARDING_APPROVAL_TITLE = "boarding_approval_title"
    const val BOARDING_APPROVAL_ACTION = "boarding_approval_action"
    const val BOARDING_IMAGE_PROMPT = "boarding_image_prompt"
    const val BOARDING_DOCUMENT_NAME = "boarding_document_name"
    const val BOARDING_SOURCE_ONE_NAME = "boarding_source_one_name"
    const val BOARDING_SOURCE_ONE_DETAIL = "boarding_source_one_detail"
    const val BOARDING_SOURCE_TWO_NAME = "boarding_source_two_name"
    const val BOARDING_SOURCE_TWO_DETAIL = "boarding_source_two_detail"
    const val BOARDING_IMAGE_EDIT = "boarding_image_edit"
    const val AUTH_LOGIN_NOTE_TITLE = "auth_login_note_title"
    const val AUTH_LOGIN_NOTE_BODY = "auth_login_note_body"
    const val AUTH_REGISTER_NOTE_TITLE = "auth_register_note_title"
    const val AUTH_REGISTER_NOTE_BODY = "auth_register_note_body"
    const val ACTION_RETRY = "action_retry"
    const val ACTION_SHOW_PASSWORD = "action_show_password"
    const val ACTION_HIDE_PASSWORD = "action_hide_password"
    const val STATUS_LOADING = "status_loading"
    const val ERROR_RUN_ACTIVE = "error_run_active"
    const val CHAT_EMPTY_TITLE = "chat_empty_title"
    const val CHAT_EMPTY_BODY = "chat_empty_body"
    const val CHAT_SESSIONS_EMPTY_TITLE = "chat_sessions_empty_title"
    const val CHAT_SESSIONS_EMPTY_BODY = "chat_sessions_empty_body"
    const val ACTION_NEW_CHAT = "action_new_chat"
    const val ACTION_SEND = "action_send"
    const val ACTION_STOP = "action_stop"
    const val ACTION_RESUME = "action_resume"
    const val COMPOSER_PLACEHOLDER = "composer_placeholder"
    const val LABEL_THOUGHT = "label_thought"
    const val CD_COPY_MESSAGE = "cd_copy_message"
    const val CD_ADD_CONTEXT = "cd_add_context"
    const val CD_EDIT_MESSAGE = "cd_edit_message"
    const val CD_REGENERATE = "cd_regenerate"
    const val CD_FEATURES = "cd_features"
    const val CD_ATTACH = "cd_attach"
    const val CD_MODEL = "cd_model"
    const val LABEL_MODEL = "label_model"
    const val LABEL_REASONING = "label_reasoning"
    const val LABEL_REASONING_NONE = "label_reasoning_none"
    const val LABEL_WEB_SEARCH = "label_web_search"
    const val LABEL_IMAGE_GEN = "label_image_gen"
    const val LABEL_ATTACH = "label_attach"
    const val LABEL_ATTACH_PHOTOS = "label_attach_photos"
    const val LABEL_ATTACH_LOCAL = "label_attach_local"
    const val LABEL_ATTACH_LIBRARY = "label_attach_library"
    const val LABEL_DOCUMENT_LIBRARY = "label_document_library"
    const val LABEL_SEARCH_DOCUMENTS = "label_search_documents"
    const val PLACEHOLDER_SEARCH_DOCUMENTS = "placeholder_search_documents"
    const val LABEL_SESSION_IMAGES = "label_session_images"
    const val IMAGE_CONTEXT_HELP = "image_context_help"
    const val CD_UNPIN_IMAGE = "cd_unpin_image"
    const val LABEL_CONTEXT_USAGE = "label_context_usage"
    const val LABEL_SEARCH = "label_search"
    const val PLACEHOLDER_SEARCH_WORKSPACE = "placeholder_search_workspace"
    const val LABEL_DOCUMENT_PREVIEW = "label_document_preview"
    const val LABEL_DOCUMENT_IMAGE = "label_document_image"
    const val LABEL_APPEARANCE = "label_appearance"
    const val APPEARANCE_SECTION_BODY = "appearance_section_body"
    const val LABEL_API_STATUS = "label_api_status"
    const val STATUS_CHECKING = "status_checking"
    const val STATUS_CONNECTED = "status_connected"
    const val STATUS_UNAVAILABLE = "status_unavailable"
    const val STATUS_UPLOAD_QUEUED = "status_upload_queued"
    const val STATUS_UPLOAD_PROCESSING = "status_upload_processing"
    const val STATUS_UPLOAD_UPLOADING = "status_upload_uploading"
    const val STATUS_UPLOAD_FAILED = "status_upload_failed"
    const val LABEL_THEME = "label_theme"
    const val LABEL_THEME_SYSTEM = "label_theme_system"
    const val LABEL_THEME_LIGHT = "label_theme_light"
    const val LABEL_THEME_DARK = "label_theme_dark"
    const val LABEL_DYNAMIC_COLOR = "label_dynamic_color"
    const val LABEL_REDUCE_MOTION = "label_reduce_motion"
    const val LABEL_REDUCE_TRANSPARENCY = "label_reduce_transparency"
    const val ATTACH_PHOTOS_BODY = "attach_photos_body"
    const val ATTACH_LOCAL_BODY = "attach_local_body"
    const val ATTACH_LIBRARY_BODY = "attach_library_body"
    const val ATTACH_LIBRARY_EMPTY = "attach_library_empty"
    const val TOAST_COPIED = "toast_copied"
    const val FEATURE_UNAVAILABLE = "feature_unavailable"
    const val CD_OPEN_CHATS = "cd_open_chats"
    const val LABEL_CHATS = "label_chats"
    const val LABEL_UNREAD = "label_unread"
    const val DIALOG_RUN_ACTIVE_TITLE = "dialog_run_active_title"
    const val ACTION_WAIT = "action_wait"
    const val ACTION_RENAME = "action_rename"
    const val ACTION_DELETE = "action_delete"
    const val ACTION_DELETING = "action_deleting"
    const val ACTION_CANCEL = "action_cancel"
    const val DIALOG_RENAME_TITLE = "dialog_rename_title"
    const val DIALOG_DELETE_TITLE = "dialog_delete_title"
    const val DIALOG_DELETE_BODY = "dialog_delete_body"
    const val DIALOG_DELETE_BODY_RUNNING = "dialog_delete_body_running"
    const val TOAST_CHAT_DELETED = "toast_chat_deleted"
    const val CD_SESSION_MENU = "cd_session_menu"
    const val ERROR_TITLE_REQUIRED = "error_title_required"
    const val LABEL_SESSION_TITLE = "label_session_title"
    const val TOOL_STATUS_WORKING = "tool_status_working"
    const val TOOL_STATUS_DONE = "tool_status_done"
    const val TOOL_STATUS_ERROR = "tool_status_error"
    const val TOOL_RUNNING_FALLBACK = "tool_running_fallback"
    const val TOOL_FIND_DOCUMENTS = "tool_find_documents"
    const val TOOL_SEARCH_DOCUMENT_PAGES = "tool_search_document_pages"
    const val TOOL_GET_DOCUMENT_NEXT_PAGE = "tool_get_document_next_page"
    const val TOOL_WEB_SEARCH = "tool_web_search"
    const val TOOL_WEB_FETCH = "tool_web_fetch"
    const val TOOL_GENERATE_IMAGE = "tool_generate_image"
    const val TOOL_EDIT_IMAGE = "tool_edit_image"
    const val TOOL_VIEW_IMAGE = "tool_view_image"
    const val TOOL_DESCRIPTIVE_STATS = "tool_descriptive_stats"
    const val ERROR_NO_ACTIVE_RUN = "error_no_active_run"
    const val ACTION_QUEUE = "action_queue"
    const val ACTION_SEND_NOW = "action_send_now"
    const val ACTION_SEND_QUEUE = "action_send_queue"
    const val ACTION_SEND_NEW_MESSAGE = "action_send_new_message"
    const val DIALOG_QUEUE_CONFLICT_TITLE = "dialog_queue_conflict_title"
    const val DIALOG_QUEUE_CONFLICT_BODY = "dialog_queue_conflict_body"
    const val LABEL_QUEUED_COUNT = "label_queued_count"
    const val LABEL_EDITING = "label_editing"
    const val CD_HIDE_QUEUE = "cd_hide_queue"
    const val CD_SHOW_QUEUE = "cd_show_queue"
    const val CD_REMOVE_QUEUED = "cd_remove_queued"
    const val CD_EXPAND_QUEUE = "cd_expand_queue"
    const val LABEL_APP_NAME = "label_app_name"
    const val LABEL_WORKSPACE = "label_workspace"
    const val LABEL_ALL_CHATS = "label_all_chats"
    const val LABEL_PROJECTS = "label_projects"
    const val LABEL_DOCUMENTS = "label_documents"
    const val LABEL_IMAGES = "label_images"
    const val LABEL_RECENT_PROJECTS = "label_recent_projects"
    const val LABEL_TODAY = "label_today"
    const val LABEL_YESTERDAY = "label_yesterday"
    const val LABEL_EARLIER = "label_earlier"
    const val CD_OPEN_DOCUMENTS = "cd_open_documents"
    const val LABEL_ACTIVE_DOCUMENTS = "label_active_documents"
    const val LABEL_CITED_DOCUMENTS = "label_cited_documents"
    const val LABEL_DOCUMENTS_NONE = "label_documents_none"
    const val LABEL_DOCUMENTS_SUMMARY = "label_documents_summary"
    const val LABEL_CITATION_COUNT = "label_citation_count"
    const val CD_REMOVE_DOCUMENT = "cd_remove_document"
    const val DOCUMENTS_EMPTY_BODY = "documents_empty_body"
    const val ACTION_SETTINGS = "action_settings"
    const val ACTION_LOG_OUT = "action_log_out"
    const val ACTION_LOGGING_OUT = "action_logging_out"
    const val CD_ACCOUNT_MENU = "cd_account_menu"
    const val CD_OPEN_ACCOUNT = "cd_open_account"
    const val CD_BACK = "cd_back"
    const val LABEL_ACCOUNT = "label_account"
    const val LABEL_USAGE = "label_usage"
    const val LABEL_PERSONALIZATION = "label_personalization"
    const val ACCOUNT_SECTION_BODY = "account_section_body"
    const val ACCOUNT_EMAIL_EMPTY = "account_email_empty"
    const val USAGE_SECTION_BODY = "usage_section_body"
    const val USAGE_EMPTY = "usage_empty"
    const val PERSONALIZATION_SECTION_BODY = "personalization_section_body"
    const val PERSONALIZATION_EMPTY = "personalization_empty"
    const val LABEL_STORAGE = "label_storage"
    const val LABEL_REQUESTS = "label_requests"
    const val LABEL_TOTAL_TOKENS = "label_total_tokens"
    const val LABEL_INPUT_TOKENS = "label_input_tokens"
    const val LABEL_OUTPUT_TOKENS = "label_output_tokens"
    const val LABEL_CACHED_TOKENS = "label_cached_tokens"
    const val LABEL_BY_MODEL = "label_by_model"
    const val LABEL_BY_REASONING = "label_by_reasoning"
    const val LABEL_PROFILE_FACTS = "label_profile_facts"
    const val LABEL_PROJECT_PROFILES = "label_project_profiles"
    const val ACTION_RESET = "action_reset"
    const val ACTION_RESETTING = "action_resetting"
    const val DIALOG_RESET_PROFILE_TITLE = "dialog_reset_profile_title"
    const val DIALOG_RESET_PROFILE_BODY = "dialog_reset_profile_body"
    const val TOAST_PROFILE_RESET = "toast_profile_reset"
    const val ACTION_NEW_PROJECT = "action_new_project"
    const val ACTION_CREATE = "action_create"
    const val LABEL_DESCRIPTION = "label_description"
    const val LABEL_IMAGE = "label_image"
    const val PROJECTS_EMPTY = "projects_empty"
    const val PROJECT_DESCRIPTION_EMPTY = "project_description_empty"
    const val DOCUMENTS_LIBRARY_EMPTY = "documents_library_empty"
    const val IMAGES_EMPTY = "images_empty"
    const val DIALOG_DELETE_WORKSPACE_TITLE = "dialog_delete_workspace_title"
    const val DIALOG_DELETE_WORKSPACE_BODY = "dialog_delete_workspace_body"
    const val ERROR_FILE_TOO_LARGE = "error_file_too_large"
    const val ERROR_FILE_READ = "error_file_read"
    const val TOAST_UPLOAD_COMPLETE = "toast_upload_complete"
    const val APPROVAL_TITLE = "approval_title"
    const val CLARIFICATION_TITLE = "clarification_title"
    const val ACTION_ALLOW_ONCE = "action_allow_once"
    const val ACTION_REJECT = "action_reject"
    const val ACTION_SUBMIT = "action_submit"

    fun get(key: String): String {
        return when (key) {
            ERROR_NO_INTERNET -> "Check your connection and try again."
            ERROR_UNAUTHORIZED -> "Sign in to continue."
            ERROR_FORBIDDEN -> "You don't have access to that."
            ERROR_NOT_FOUND -> "We couldn't find that."
            ERROR_TIMEOUT -> "That took too long. Try again."
            ERROR_CONFLICT -> "That conflicts with the current state. Try again."
            ERROR_TOO_MANY_REQUESTS -> "Too many attempts. Wait a moment and try again."
            ERROR_SERVER -> "The server had a problem. Try again."
            ERROR_UNKNOWN -> "Something went wrong. Try again."
            ERROR_DISK_FULL -> "Not enough storage to finish that."
            ERROR_INVALID_EMAIL -> "Enter a valid email address."
            ERROR_PASSWORD_TOO_SHORT -> "Password must be at least 8 characters."
            ERROR_PASSWORD_MISMATCH -> "Passwords do not match."
            ERROR_NAME_REQUIRED -> "Name is required."
            ERROR_INVALID_CREDENTIALS -> "Invalid email or password."
            ERROR_EMAIL_TAKEN -> "An account with that email already exists."
            ERROR_SIGN_IN_FAILED -> "Could not sign in. Check your connection and try again."
            ERROR_SIGN_UP_FAILED -> "Could not create an account. Try again."
            LABEL_EMAIL -> "Email"
            LABEL_PASSWORD -> "Password"
            LABEL_NAME -> "Name"
            LABEL_CONFIRM_PASSWORD -> "Confirm password"
            ACTION_CONTINUE -> "Continue"
            ACTION_SIGNING_IN -> "Signing in…"
            ACTION_CREATE_ACCOUNT -> "Create account"
            ACTION_CREATING_ACCOUNT -> "Creating account…"
            ACTION_SIGN_IN -> "Sign in"
            AUTH_HAVE_ACCOUNT -> "Already have an account?"
            AUTH_NEW_HERE -> "New here?"
            LOGIN_TITLE -> "Welcome back"
            LOGIN_SUBTITLE -> "Sign in to continue with your documents, sources, and project context."
            REGISTER_TITLE -> "Build your private workspace"
            REGISTER_SUBTITLE -> "Create one account for grounded chats, research, and visual work."
            PLACEHOLDER_EMAIL -> "you@company.com"
            PLACEHOLDER_PASSWORD -> "Your password"
            PLACEHOLDER_NAME -> "Ada Lovelace"
            PLACEHOLDER_PASSWORD_NEW -> "At least 8 characters"
            PLACEHOLDER_PASSWORD_REPEAT -> "Repeat your password"
            SPLASH_VERSION -> "Anreal v{0}"
            SPLASH_CREDIT -> "Presented by Ratmo.co"
            CD_APP_MARK -> "Anreal"
            BOARDING_DOCUMENTS_TITLE -> "Ask, then verify"
            BOARDING_DOCUMENTS_BODY ->
                "Ground every answer in your files and jump straight to the cited page."
            BOARDING_WEB_TITLE -> "Research on your terms"
            BOARDING_WEB_BODY ->
                "Bring in fresh web sources only when you allow it, without leaving the thread."
            BOARDING_IMAGES_TITLE -> "Turn context into visuals"
            BOARDING_IMAGES_BODY ->
                "Generate, edit, and organize images beside the chats and projects that shaped them."
            CD_BOARDING_PAGE -> "Feature {0} of {1}"
            BOARDING_USER_PROMPT -> "Where is the renewal risk?"
            BOARDING_ASSISTANT_REPLY ->
                "Two enterprise accounts are delayed."
            BOARDING_CITATION -> "Board pack · pp. 12–14"
            BOARDING_WEB_TOOL -> "Recent renewal coverage"
            BOARDING_WEB_SOURCE -> "4 cited sources · last 30 days"
            BOARDING_IMAGE_CAPTION -> "Saved to Q3 review"
            BOARDING_TAGLINE -> "A private AI workspace"
            BOARDING_APPROVAL_TITLE -> "Web search needs your approval"
            BOARDING_APPROVAL_ACTION -> "Allow once"
            BOARDING_IMAGE_PROMPT -> "Create a clean risk heatmap"
            BOARDING_DOCUMENT_NAME -> "Board pack.pdf"
            BOARDING_SOURCE_ONE_NAME -> "Reuters"
            BOARDING_SOURCE_ONE_DETAIL -> "Renewal outlook"
            BOARDING_SOURCE_TWO_NAME -> "Trade brief"
            BOARDING_SOURCE_TWO_DETAIL -> "Enterprise cycles"
            BOARDING_IMAGE_EDIT -> "Edit in the same thread"
            AUTH_LOGIN_NOTE_TITLE -> "Pick up where you left off"
            AUTH_LOGIN_NOTE_BODY -> "Your chats, sources, and project context stay together."
            AUTH_REGISTER_NOTE_TITLE -> "Private by default"
            AUTH_REGISTER_NOTE_BODY -> "Your documents and chats stay inside your account."
            ACTION_RETRY -> "Retry"
            ACTION_SHOW_PASSWORD -> "Show password"
            ACTION_HIDE_PASSWORD -> "Hide password"
            STATUS_LOADING -> "Loading"
            ERROR_RUN_ACTIVE -> "This chat is already running. Resume it or wait for it to finish."
            ERROR_STORAGE_QUOTA -> "Document storage is full. Delete a document before uploading another file."
            ERROR_DOCUMENT_INGEST -> "The document could not be processed. Try uploading it again."
            ERROR_IMAGE_LOAD -> "The image could not be loaded."
            ERROR_REGENERATE_UNAVAILABLE -> "This message cannot be regenerated yet. Reload the conversation and try again."
            ERROR_SESSION_STALE -> "This conversation changed elsewhere. The latest messages have been reloaded."
            CHAT_EMPTY_TITLE -> "Ask anything about your documents"
            CHAT_EMPTY_BODY -> "Upload a PDF or image, then ask questions."
            CHAT_SESSIONS_EMPTY_TITLE -> "No chats yet"
            CHAT_SESSIONS_EMPTY_BODY -> "Start a conversation about your documents."
            ACTION_NEW_CHAT -> "New chat"
            ACTION_SEND -> "Send"
            ACTION_STOP -> "Stop"
            ACTION_LOAD_MORE -> "Load more"
            ACTION_ATTACH -> "Attach"
            ACTION_CLOSE -> "Close"
            ACTION_PREVIOUS -> "Previous page"
            ACTION_NEXT -> "Next page"
            ACTION_RESUME -> "Resume"
            COMPOSER_PLACEHOLDER -> "Ask about your documents…"
            CD_OPEN_CHATS -> "Open chats"
            LABEL_THOUGHT -> "Thought for a moment"
            CD_COPY_MESSAGE -> "Copy message"
            CD_ADD_CONTEXT -> "Add as context"
            CD_EDIT_MESSAGE -> "Edit message"
            CD_REGENERATE -> "Regenerate from this message"
            CD_FEATURES -> "Additional features"
            CD_ATTACH -> "Attach"
            CD_MODEL -> "Model and reasoning"
            LABEL_MODEL -> "Model"
            LABEL_REASONING -> "Reasoning"
            LABEL_REASONING_NONE -> "None"
            LABEL_WEB_SEARCH -> "Web search"
            LABEL_IMAGE_GEN -> "Image generate"
            LABEL_ATTACH -> "Add to this chat"
            LABEL_ATTACH_PHOTOS -> "Photos"
            LABEL_ATTACH_LOCAL -> "Local document"
            LABEL_ATTACH_LIBRARY -> "Uploaded files"
            LABEL_DOCUMENT_LIBRARY -> "Document library"
            LABEL_SEARCH_DOCUMENTS -> "Search documents"
            PLACEHOLDER_SEARCH_DOCUMENTS -> "Name or summary"
            LABEL_SESSION_IMAGES -> "Images"
            IMAGE_CONTEXT_HELP -> "Tap to pin as context"
            CD_UNPIN_IMAGE -> "Unpin image from context"
            LABEL_CONTEXT_USAGE -> "Context"
            LABEL_SEARCH -> "Search"
            PLACEHOLDER_SEARCH_WORKSPACE -> "Name or summary"
            LABEL_DOCUMENT_PREVIEW -> "Document preview"
            LABEL_DOCUMENT_IMAGE -> "Document page image"
            LABEL_APPEARANCE -> "Appearance"
            APPEARANCE_SECTION_BODY -> "Choose how Anreal looks and responds to motion preferences."
            LABEL_API_STATUS -> "API status"
            STATUS_CHECKING -> "Checking…"
            STATUS_CONNECTED -> "Connected"
            STATUS_UNAVAILABLE -> "Unavailable"
            STATUS_UPLOAD_QUEUED -> "Queued"
            STATUS_UPLOAD_PROCESSING -> "Processing"
            STATUS_UPLOAD_UPLOADING -> "Uploading"
            STATUS_UPLOAD_FAILED -> "Failed"
            LABEL_THEME -> "Theme"
            LABEL_THEME_SYSTEM -> "System"
            LABEL_THEME_LIGHT -> "Light"
            LABEL_THEME_DARK -> "Dark"
            LABEL_DYNAMIC_COLOR -> "Use wallpaper colors"
            LABEL_REDUCE_MOTION -> "Reduce motion"
            LABEL_REDUCE_TRANSPARENCY -> "Reduce transparency"
            ATTACH_PHOTOS_BODY -> "Images from this device"
            ATTACH_LOCAL_BODY -> "PDF or image from this device"
            ATTACH_LIBRARY_BODY -> "Pick from your document library"
            ATTACH_LIBRARY_EMPTY -> "No documents are available to attach."
            TOAST_COPIED -> "Copied"
            FEATURE_UNAVAILABLE -> "Not configured on this server."
            LABEL_CHATS -> "Chats"
            LABEL_UNREAD -> "Unread"
            DIALOG_RUN_ACTIVE_TITLE -> "Chat already running"
            ACTION_WAIT -> "Wait"
            ACTION_RENAME -> "Rename"
            ACTION_DELETE -> "Delete"
            ACTION_DELETING -> "Deleting…"
            ACTION_CANCEL -> "Cancel"
            DIALOG_RENAME_TITLE -> "Rename chat"
            DIALOG_DELETE_TITLE -> "Delete chat"
            DIALOG_DELETE_BODY -> "This removes the conversation. Documents and preferences are not affected."
            DIALOG_DELETE_BODY_RUNNING -> "The running reply will stop."
            TOAST_CHAT_DELETED -> "Chat deleted"
            CD_SESSION_MENU -> "Chat actions"
            ERROR_TITLE_REQUIRED -> "Enter a name for this chat."
            LABEL_SESSION_TITLE -> "Name"
            TOOL_STATUS_WORKING -> "Working"
            TOOL_STATUS_DONE -> "Done"
            TOOL_STATUS_ERROR -> "Error"
            TOOL_RUNNING_FALLBACK -> "Running {0}"
            TOOL_FIND_DOCUMENTS -> "Finding documents"
            TOOL_SEARCH_DOCUMENT_PAGES -> "Searching document pages"
            TOOL_GET_DOCUMENT_NEXT_PAGE -> "Reading next page"
            TOOL_WEB_SEARCH -> "Searching the web"
            TOOL_WEB_FETCH -> "Fetching web page"
            TOOL_GENERATE_IMAGE -> "Generating image"
            TOOL_EDIT_IMAGE -> "Editing image"
            TOOL_VIEW_IMAGE -> "Viewing image"
            TOOL_DESCRIPTIVE_STATS -> "Computing statistics"
            ERROR_NO_ACTIVE_RUN -> "That run already finished. Send this as a new message."
            ACTION_QUEUE -> "Queue"
            ACTION_SEND_NOW -> "Send now"
            ACTION_SEND_QUEUE -> "Send queue"
            ACTION_SEND_NEW_MESSAGE -> "Send new message"
            DIALOG_QUEUE_CONFLICT_TITLE -> "Send now or keep the queue?"
            DIALOG_QUEUE_CONFLICT_BODY -> "You have follow-ups waiting. Send the queue first, or send this new message and hold the queue."
            LABEL_QUEUED_COUNT -> "{0} queued"
            LABEL_EDITING -> "Editing…"
            CD_HIDE_QUEUE -> "Hide queue"
            CD_SHOW_QUEUE -> "Show queue"
            CD_REMOVE_QUEUED -> "Remove queued message"
            CD_EXPAND_QUEUE -> "Show all queued messages"
            LABEL_APP_NAME -> "Anreal"
            LABEL_WORKSPACE -> "Workspace"
            LABEL_ALL_CHATS -> "All chats"
            LABEL_PROJECTS -> "Projects"
            LABEL_DOCUMENTS -> "Documents"
            LABEL_IMAGES -> "Images"
            LABEL_RECENT_PROJECTS -> "Recent projects"
            LABEL_TODAY -> "Today"
            LABEL_YESTERDAY -> "Yesterday"
            LABEL_EARLIER -> "Earlier"
            CD_OPEN_DOCUMENTS -> "Session documents"
            LABEL_ACTIVE_DOCUMENTS -> "Active documents"
            LABEL_CITED_DOCUMENTS -> "Cited documents"
            LABEL_DOCUMENTS_NONE -> "None yet"
            LABEL_DOCUMENTS_SUMMARY -> "{0} active · {1} cited"
            LABEL_CITATION_COUNT -> "{0} citations"
            CD_REMOVE_DOCUMENT -> "Remove from this chat"
            DOCUMENTS_EMPTY_BODY -> "Attach a file or pick from your library to ground this chat."
            ACTION_SETTINGS -> "Settings"
            ACTION_LOG_OUT -> "Log out"
            ACTION_LOGGING_OUT -> "Signing out…"
            CD_ACCOUNT_MENU -> "Account menu"
            CD_OPEN_ACCOUNT -> "Open account"
            CD_BACK -> "Back"
            LABEL_ACCOUNT -> "Account"
            LABEL_USAGE -> "Usage"
            LABEL_PERSONALIZATION -> "Personalization"
            ACCOUNT_SECTION_BODY -> "Profile details for this workspace."
            ACCOUNT_EMAIL_EMPTY -> "No email on this account."
            USAGE_SECTION_BODY -> "Storage, tokens, and how you use models and reasoning."
            USAGE_EMPTY -> "No chat requests yet. Model and reasoning mix will appear here."
            PERSONALIZATION_SECTION_BODY ->
                "What the assistant knows about you, built automatically from your chats. Reset anytime to start fresh."
            PERSONALIZATION_EMPTY -> "No profile yet. It builds automatically from your chats."
            LABEL_STORAGE -> "Storage"
            LABEL_REQUESTS -> "Requests"
            LABEL_TOTAL_TOKENS -> "Total tokens"
            LABEL_INPUT_TOKENS -> "Input"
            LABEL_OUTPUT_TOKENS -> "Output"
            LABEL_CACHED_TOKENS -> "Cached input"
            LABEL_BY_MODEL -> "By model"
            LABEL_BY_REASONING -> "By reasoning"
            LABEL_PROFILE_FACTS -> "Your profile"
            LABEL_PROJECT_PROFILES -> "Project profiles"
            ACTION_RESET -> "Reset"
            ACTION_RESETTING -> "Resetting…"
            DIALOG_RESET_PROFILE_TITLE -> "Reset personalization?"
            DIALOG_RESET_PROFILE_BODY ->
                "This permanently removes the learned profile. New chats can build it again."
            TOAST_PROFILE_RESET -> "Personalization reset"
            ACTION_NEW_PROJECT -> "New project"
            ACTION_CREATE -> "Create"
            LABEL_DESCRIPTION -> "Description"
            LABEL_IMAGE -> "Image"
            PROJECTS_EMPTY -> "No projects yet. Create one to keep related chats and sources together."
            PROJECT_DESCRIPTION_EMPTY -> "No description"
            DOCUMENTS_LIBRARY_EMPTY -> "No documents in your library yet. Attach one from a chat."
            IMAGES_EMPTY -> "No generated or uploaded images yet."
            DIALOG_DELETE_WORKSPACE_TITLE -> "Delete item?"
            DIALOG_DELETE_WORKSPACE_BODY -> "Delete {0}? This cannot be undone."
            ERROR_FILE_TOO_LARGE -> "Files must be 10 MB or smaller."
            ERROR_FILE_READ -> "Could not read that file."
            TOAST_UPLOAD_COMPLETE -> "Upload started. It will appear when processing is ready."
            APPROVAL_TITLE -> "Approval required"
            CLARIFICATION_TITLE -> "A little more detail"
            ACTION_ALLOW_ONCE -> "Allow once"
            ACTION_REJECT -> "Reject"
            ACTION_SUBMIT -> "Submit"
            else -> key
        }
    }
}

fun UiText.asString(): String {
    return when (this) {
        is UiText.DynamicString -> value
        is UiText.StringResource -> interpolate(AnrealCopy.get(key), args)
    }
}

internal fun interpolate(template: String, args: List<String>): String {
    return args.foldIndexed(template) { index, acc, arg ->
        acc.replace("{$index}", arg)
    }
}
